### ISSUE TITLE
Tibble printing in console is FUBAR after updating tidyverse

### ISSUE THREAD

**Issue by daltonhance** [tidyverse/tidyverse#103]
I just updated to the newest version of tidyverse and tibble printing in console in RStudio is significantly different and is nigh on unreadable. Long variables names are annoyingly abbreviated with a tilde. Variable names and data columns are not aligned. Very strange color choices and highlighting.

Example here: 
![image](https://user-images.githubusercontent.com/12704795/34584111-49e878a8-f14f-11e7-9139-9b7c1690dbfb.png)

It isn't even self-consistent. Here is the tail of the same tibble:
![image](https://user-images.githubusercontent.com/12704795/34584187-a5e42152-f14f-11e7-9d18-d40a95f23e79.png)

And the same output after resizing the console window in RStudio:
![image](https://user-images.githubusercontent.com/12704795/34584231-c5c367a8-f14f-11e7-8623-5f7d045b2b2e.png)

RStudio version: 1.1.383 

Session info:
![image](https://user-images.githubusercontent.com/12704795/34584301-0c5bc8d6-f150-11e7-95eb-a49e2fb87889.png)

**Comment by jbellegarde-p2r** [comment]
I don't agree it is FUBAR, but it is not my favorite look. 
I don't understand why specific numbers are white and certain ones are grey... Sometimes it is the 1 digit, sometimes the 10 digit, sometimes some other digit. Makes it hard to read.
Not a fan of the column name trunc.
Seems random how each column's width is decided.
I like the NA highlighting, that's cool.

**Comment by hadley** [comment]
See the posts on https://www.tidyverse.org/articles/ about pillar and tibble.
