### ISSUE TITLE
Pretty load and conflict tables for all packages

### ISSUE THREAD

**Issue by d8aninja** [tidyverse/tidyverse#104]
If tidyverse is loaded up front in any manner (directly, with a call to `library(tidyverse)`, or as a dependency) it would be nice if other, non-tidyverse packages were treated with the same pretty tables with version numbers.  `tidyverse_conflicts` seems to have the expected behavior, even in light of this hopeful change, since it shows the nice `a masks b` format for all packages regardless of their tidyverse relationship

```
[dtg:20180105202456] .R> library(tidyverse)
── Attaching packages 
──────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 2.2.1     ✔ purrr   0.2.4
✔ tibble  1.3.4     ✔ dplyr   0.7.4
✔ tidyr   0.7.2     ✔ stringr 1.2.0
✔ readr   1.1.1     ✔ forcats 0.2.0
── Conflicts 
──────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

[dtg:20180105202456] .R> library(jsonlite)

Attaching package: ‘jsonlite’

The following object is masked from ‘package:purrr’:

    flatten

[dtg:20180105202456] .R> tidyverse_conflicts()
── Conflicts 
──────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter()     masks stats::filter()
✖ jsonlite::flatten() masks purrr::flatten()
✖ dplyr::lag()        masks stats::lag()
```

**Comment by hadley** [comment]
This is out of scope for the tidyverse, but this is definitely something to contemplate for more informative package loading in general.
