### ISSUE TITLE
Error: Loading package failed with message "there is no package called 'pillar'"

### ISSUE THREAD

**Issue by jrosen48** [tidyverse/tidyverse#105]
When installing tidyverse with `install.packages("tidyverse") and then loading with `library(tidyverse)`, the following error is returned:

```
> library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘pillar’
```

When I ran `devtools::install_github("r-lib/pillar")`, and then`library(tidyverse)`, the package loads normally.

**Comment by hadley** [comment]
This is unfortunately because `install.packages()` occasionally fails to install one of the recursive dependencies.
