### ISSUE TITLE
Need better word than API

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyverse#107]
Let's use grammar

**Comment by jennybc** [comment]
What exactly are we talking about? Without knowing that, I'll still boldly offer "interface" or "user interface" as another option.

**Comment by hadley** [comment]
On the home page

**Comment by jennybc** [comment]
OK so maybe we're talking about this sentence from <https://www.tidyverse.org>:

> All packages share an underlying philosophy and common APIs.

Or, at least, sentences derived from that.

Maybe: "All packages share a common design philosophy and data model."?

Data-model-wise, we're alluding to:

Store data
Keep it tidy
Mostly data frames

And the philosophy part is a nod to consistency, predictability, pit of success.

**Comment by hadley** [comment]
Yes, sorry for terseness. 

Maybe: All packages share a common design philosophy, grammar, and data model.

I wanted to explicit highlight consistency of syntax, because I think that's important. After #108, we should link to that page.

**Comment by jennybc** [comment]
Are we talking about prose inside the tidyverse package (this repo) or on the tidyverse website? This has been part of my confusion, because it seems like the latter.

**Comment by batpigandme** [comment]
@jennybc I think site…

**Comment by hadley** [comment]
Oh shoot, I filed it in the wrong place 😿
