### ISSUE TITLE
Port manifesto from tidyverse package

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyverse#108]
i.e. https://cran.r-project.org/web/packages/tidyverse/vignettes/manifesto.html

Probably fine as is, but worth a pass from @batpigandme + @jennybc, and at least file issues to follow up on the big things that we think are missing

**Comment by njtierney** [comment]
Apologies if I'm butting in here, but it seems like this part of the manifesto under "reuse existing data structures" might need updating?

> If you need “non-standard scoping”, where you refer to variables inside a data frame as if they are in the global environment, prefer formulas over non-standard evaluation. See lazyeval for more details.

**Comment by hadley** [comment]
This was filed in the wrong place.
