### ISSUE TITLE
Submit tverse 📦 to JOSS

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse#111]
per HW request: look into submitting tidyverse package to JOSS/ That would be nice thing for people to cite. We might need to adjust authors on package first though

**Comment by hadley** [comment]
And once in JOSS, we should make add this to `inst/CITATION` for all tidyverse packages, which probably also means make `use_tidy_citation()`.

Then I think we can give compelling citation advice - if you cite the tidyverse as a whole, then only you need to individual packages if they were particularly important to the analysis (e.g. probably only ggplot2 and/or dplyr)

**Comment by hadley** [comment]
Let me take this one

**Comment by hadley** [comment]
* [ ] A list of the authors of the software and their affiliations
* [ ] A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
* [ ] A clear statement of need that illustrates the purpose of the software
* [ ] A list of key references including a link to the software archive
* [ ] Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it
