### ISSUE TITLE
stringr::str_order seems not to return the right integers

### ISSUE THREAD

**Issue by carioca67** [tidyverse/tidyverse#115]
a simple call to str_order does not seem to return the right ordering:

```{r}
str_order(c("xyz","abc","def","ghi","abc"))
```
>2 5 3 4 1

whereas I would expect 5 1 3 4 2

however, str_sort does the right job. weird.

**Comment by jennybc** [comment]
I'm not sure why you expect 5, 1, 3, 4, 2.

``` r
x <- c("xyz","abc","def","ghi","abc")
stringr::str_sort(x)
#> [1] "abc" "abc" "def" "ghi" "xyz"
stringr::str_order(x)
#> [1] 2 5 3 4 1
x[stringr::str_order(x)]
#> [1] "abc" "abc" "def" "ghi" "xyz"
```

Created on 2018-02-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Also, just so you know for future, it would be best to open an issue on the [stringr package](https://github.com/tidyverse/stringr/issues) itself or, in this case, ask a question in the [tidyverse channel](https://community.rstudio.com/c/tidyverse) at community.rstudio.com.
