### ISSUE TITLE
callr package failing to install

### ISSUE THREAD

**Issue by Fredo-XVII** [tidyverse/tidyverse#116]
Hello,

I wanted to let you know that the callr package is failing to install.  I don't know what this means for the other packages as a whole, but I thought you should know.  

I am on a lenovo windows 64bit machine with 16GBs of RAM.

I will paste the output below.

> install.packages("tidyverse")
also installing the dependencies ‘callr’, ‘ggplot2’, ‘haven’, ‘hms’, ‘lubridate’, ‘modelr’, ‘readr’, ‘readxl’, ‘reprex’, ‘rvest’, ‘tidyr’, ‘xml2’

  There is a binary version available but the source version is later:
      binary source needs_compilation
callr  2.0.1  2.0.2              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/callr_2.0.1.zip'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/callr_2.0.1.zip': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/callr_2.0.1.zip'
Warning in install.packages :
  download of package ‘callr’ failed

... other packages install ...

package ‘ggplot2’ successfully unpacked and MD5 sums checked
package ‘haven’ successfully unpacked and MD5 sums checked
package ‘hms’ successfully unpacked and MD5 sums checked
package ‘lubridate’ successfully unpacked and MD5 sums checked
package ‘modelr’ successfully unpacked and MD5 sums checked
package ‘readr’ successfully unpacked and MD5 sums checked
package ‘readxl’ successfully unpacked and MD5 sums checked
package ‘reprex’ successfully unpacked and MD5 sums checked
package ‘rvest’ successfully unpacked and MD5 sums checked
package ‘tidyr’ successfully unpacked and MD5 sums checked
package ‘xml2’ successfully unpacked and MD5 sums checked
package ‘tidyverse’ successfully unpacked and MD5 sums checked

**Comment by hadley** [comment]
You probably unluckily tried to install at a point in time when the CRAN mirror was synching. I don't think this is a common problem.
