### ISSUE TITLE
Issues installing tidyverse Linux 

### ISSUE THREAD

**Issue by ljmills** [tidyverse/tidyverse#118]
installing to /panfs/roc/groups/4/ljmills/ljmills/R/x86_64-pc-linux-gnu-library/3.4/haven/libs
** R
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/panfs/roc/groups/4/ljmills/ljmills/R/x86_64-pc-linux-gnu-library/3.4/rlang/libs/rlang.so':
  libimf.so: cannot open shared object file: No such file or directory
ERROR: lazy loading failed for package ‘haven’
* removing ‘/panfs/roc/groups/4/ljmills/ljmills/R/x86_64-pc-linux-gnu-library/3.4/haven’
ERROR: dependency ‘haven’ is not available for package ‘tidyverse’
* removing ‘/panfs/roc/groups/4/ljmills/ljmills/R/x86_64-pc-linux-gnu-library/3.4/tidyverse’

The downloaded source packages are in
	‘/tmp/RtmpiQRqnL/downloaded_packages’
Warning messages:
1: In install.packages("tidyverse") :
  installation of package ‘haven’ had non-zero exit status
2: In install.packages("tidyverse") :
  installation of package ‘tidyverse’ had non-zero exit status

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS: /panfs/roc/msisoft/R/3.4.3/lib64/R/lib/libRblas.so
LAPACK: /panfs/roc/msisoft/R/3.4.3/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_0.12.15

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3

**Comment by hadley** [comment]
You'll need to install rlang by hand.

**Comment by serine** [comment]
@hadley can you elaborate a bit more? I'm having the same issue

```Error: package or namespace load failed for ‘readxl’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/kirill/R/x86_64-conda_cos6-linux-gnu-library/3.5/readxl/libs/readxl.so':
  /home/kirill/R/x86_64-conda_cos6-linux-gnu-library/3.5/readxl/libs/readxl.so: undefined symbol: libiconv
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/kirill/R/x86_64-conda_cos6-linux-gnu-library/3.5/readxl’
ERROR: dependencies ‘haven’, ‘readxl’ are not available for package ‘tidyverse’
* removing ‘/home/kirill/R/x86_64-conda_cos6-linux-gnu-library/3.5/tidyverse’

The downloaded source packages are in
        ‘/tmp/RtmpueGOTu/downloaded_packages’
Warning messages:
1: In install.packages("tidyverse") :
  installation of package ‘haven’ had non-zero exit status
2: In install.packages("tidyverse") :
  installation of package ‘readxl’ had non-zero exit status
3: In install.packages("tidyverse") :
  installation of package ‘tidyverse’ had non-zero exit status
```

```(ins)[precision-tower]~/test2$ dpkg -l | grep libiconv
ii  libiconv-hook-dev                          0.0.20021209-11                              amd64        header files of libiconv-hook
ii  libiconv-hook1                             0.0.20021209-11                              amd64        extension of iconv for libapache-mod-encoding
```

I don't understand why one would need full `rlang`, but if one does can you provide "typical" ubuntu/debian command to install?

Cheers

**Comment by hadley** [comment]
@serine your problem looks unrelated. I'd recommend asking on http://community.rstudio.com/

**Comment by serine** [comment]
right, so the case above different library was missing. I see that now. This isn't the first time I'm hitting this problem. I think this is to do with how `conda` manages/changes environment. 

I found the solution [here](https://github.com/tidyverse/haven/issues/363)

```withr::with_makevars(c(PKG_LIBS = "-liconv"), install.packages("haven"), assignment = "+=")```

cheers

**Comment by jennybc** [comment]
@serine You might be interested in @jimhester's advice re: Conda:

https://whattheyforgot.org/set-up-an-r-dev-environment.html#what-about-conda
