### ISSUE TITLE
[feature request] How do I write my own tidyverse?

### ISSUE THREAD

**Issue by BenoitLondon** [tidyverse/tidyverse#126]
Maybe should be in devtools...
Basically I have a bunch of private packages (and maybe public) that I would like to bundle in one package in the same way as tidyverse so that I can load or update them in one command.

Is there a recommended way or should I edit tidyverse to work with my packages?
I imagine a function like `verse_packages(package_name, packages)`

**Comment by hadley** [comment]
I think this is currently out of scope - I'm not ever 100% sure that the tidyverse package approach is the right idea.
