### ISSUE TITLE
Tidyverse startup message causes pdf output with pdflatex to fail

### ISSUE THREAD

**Issue by rmcd1024** [tidyverse/tidyverse#127]
The following document fails to compile in rstudio using default settings. The error message is `Package inputenc Error: Unicode char √ (U+221A)`.

 ```
     ---
     output: pdf_document
     ---
     a
     ```
     library(tidyverse)  
     ```
```
There are several workarounds:
* `options(tidyverse.quiet=TRUE)`
* chunk option `include=FALSE`
* `latex_engine: xelatex` (pdflatex is the default in rstudio)

However, I'm struggling to understand why all of this is necessary. Why does the startup message need to use unicode? Why doesn't tidyverse respect the `library(quietly=TRUE)` option?

If the startup behavior remains unchanged, shouldn't the documentation mention this issue prominently? (Just to be clear, this is not a hypothetical issue, this caused ongoing problems in a class I taught using tidyverse. I had no idea where the unicode was coming from.)

**Comment by hadley** [comment]
See docs for why `library(quietly = TRUE)` doesn't work: 

> If `TRUE`, no message confirming package attaching is printed, and most often, no errors/warnings are printed if package attaching fails.

The unicode characters should be automatically suppressed when you use knitr, but unfortunately there's a bug in cli: https://github.com/r-lib/cli/issues/34
