### ISSUE TITLE
Should DESCRIPTION specify minimum versions?

### ISSUE THREAD

**Issue by davharris** [tidyverse/tidyverse#13]
It seems like this would make it easier to make sure that the supported packages are all up to date (especially on larger shared machines where we have to ask IT to update packages one at a time).

If this is a good idea, I'd be happy to write a script that would find the most recent CRAN version numbers.

**Comment by hrbrmstr** [comment]
No need to write a script:

http://stackoverflow.com/questions/38686427/determine-minimum-r-version-for-all-package-dependencies

http://stackoverflow.com/questions/38738292/how-can-i-automatically-add-update-depends-imports-suggests-versions-in-descript/38743324#38743324

**Comment by davharris** [comment]
Good points. Closing.
