### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by Selvamjn** [tidyverse/tidyverse#132]
ERROR: configuration failed for package ‘xml2’
* removing ‘/home/selvam/R/x86_64-pc-linux-gnu-library/3.4/xml2’
Warning in install.packages :
  installation of package ‘xml2’ had non-zero exit status
ERROR: dependency ‘xml2’ is not available for package ‘rvest’
* removing ‘/home/selvam/R/x86_64-pc-linux-gnu-library/3.4/rvest’
Warning in install.packages :
  installation of package ‘rvest’ had non-zero exit status
ERROR: dependencies ‘rvest’, ‘xml2’ are not available for package ‘tidyverse’
* removing ‘/home/selvam/R/x86_64-pc-linux-gnu-library/3.4/tidyverse’
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpi3Jhpr/downloaded_packages’

**Comment by batpigandme** [comment]
What happens if  you try installing xml2 on its own, then installing the tidyverse package?

**Comment by Selvamjn** [comment]
I get below error
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libxml-2.0 was not found. Try installing:
 * deb: libxml2-dev (Debian, Ubuntu, etc)
 * rpm: libxml2-devel (Fedora, CentOS, RHEL)
 * csw: libxml2_dev (Solaris)
If libxml-2.0 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libxml-2.0.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘xml2’
* removing ‘/home/selvam/R/x86_64-pc-linux-gnu-library/3.4/xml2’
Installation failed: Command failed (1)

**Comment by batpigandme** [comment]
OK, per the error message, you need libxml installed and in your path. 

Since tidyverse is a meta package, I'm going to close this issue - I don't think you should have trouble with xml2 once you've got libxml squared away, but feel free to ask over on community.rstudio.com for help.
