### ISSUE TITLE
Automatically use conflicts

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyverse#135]
Need to give it a bit more time for any issues to crop up but seems like it will be more useful than harmful.

**Comment by hadley** [comment]
And consider adding lubridate

**Comment by jtelleria** [comment]
It would be nice to see an conflicted::enable_conflicted() function. Maybe conflicted first could be included disabled, and with time enable it by default for a safer approach.

**Comment by batpigandme** [comment]
> It would be nice to see an `conflicted::enable_conflicted()` function. 

This request would fit better in the conflicted repo.

**Comment by jtelleria** [comment]
Done.

**Comment by hadley** [comment]
Putting this on indefinite hold due to changes in how R manages conflicts in 3.6
