### ISSUE TITLE
Problem installing Tydiverse due to R version

### ISSUE THREAD

**Issue by osmelmillan** [tidyverse/tidyverse#137]
I received the following message when I try to install the TYDIVERSE package on R: 
_> install.packages("tydiverse")
Installing package into ‘C:/Users/Usuario/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘tydiverse’ is not available (for R version 3.5.0)_

I even made tries with previous versions up to 3.3.0 having similar message (only changing the versión numbering). 

Any help?

**Comment by batpigandme** [comment]
This is because you have `install.packages("tydiverse")` instead of `install.packages("tidyverse")`. Just a spelling error. ✔

**Comment by osmelmillan** [comment]
LOL thanks
