### ISSUE TITLE
Tidyverse not working

### ISSUE THREAD

**Issue by osmelmillan** [tidyverse/tidyverse#138]
I am getting the following message trying to work with tidyverse:
_Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘lubridate’_

Previously I had no problem. I did install.packages("lubridate"), and after that tidyverse does not work any more, maybe that is what is affecting. Please How to fix?

**Comment by batpigandme** [comment]
It sounds like lubridate didn't install correctly. Could you please ask this over on community.rstudio.com? I don't think it's a bug with tidyverse, so that'll be a better place to troubleshoot, and, if it turns out to be, we can reopen your issue here with more information. 🙂
