### ISSUE TITLE
Incorrect output from `tidyverse_packages()`

### ISSUE THREAD

**Issue by psychelzh** [tidyverse/tidyverse#146]
Here is the output of `tidyverse_packages()`, and the strange string `"readxl\n(>="` should be fixed, which I believe should be `"readxl"` instead.

``` r
tidyverse::tidyverse_packages()
#>  [1] "broom"       "cli"         "crayon"      "dplyr"       "dbplyr"     
#>  [6] "forcats"     "ggplot2"     "haven"       "hms"         "httr"       
#> [11] "jsonlite"    "lubridate"   "magrittr"    "modelr"      "purrr"      
#> [16] "readr"       "readxl\n(>=" "reprex"      "rlang"       "rstudioapi" 
#> [21] "rvest"       "stringr"     "tibble"      "tidyr"       "xml2"       
#> [26] "tidyverse"
```

Created on 2018-07-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by batpigandme** [comment]
Hi this has already been resolved in the development version, and will be fixed in the next CRAN release, see:
https://github.com/tidyverse/tidyverse/issues/142#issuecomment-402441365
