### ISSUE TITLE
Merge the multiple Excel files with multiple sheets

### ISSUE THREAD

**Issue by sampath2510** [tidyverse/tidyverse#147]
I have multiple Excel files where each one has contain three sheets and need to merge file as sheets wise.. couldn't able to work out with the map and readxl function..

Please anyone help me to figure out and share the code if possible

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by jennybc** [comment]
This article presents some very relevant workflows:

https://readxl.tidyverse.org/articles/articles/readxl-workflows.html
