### ISSUE TITLE
Red Xs in startup message too strong?

### ISSUE THREAD

**Issue by malcolmbarrett** [tidyverse/tidyverse#149]
Recently, I was working with some newcomers to the tidyverse. One thing I noticed several times was students being confused by the red Xs for the masking warnings. Some of this, of course, is learning how R loads packages and functions. But they were under the belief that something was wrong, and I was asked how to fix it a few times.

I think the message as is is good, but perhaps the red Xs could be replaced by something a little softer that looks more like a warning than an error.

**Comment by hadley** [comment]
The conflicts message will go away in the next release since the tidyverse is going to attach conflicted.
