### ISSUE TITLE
library(tidyverse, quietly=TRUE, warn.conflicts=FALSE) isn't quiet and shows conflicts.

### ISSUE THREAD

**Issue by tmalsburg** [tidyverse/tidyverse#151]
library(tidyverse, quietly=TRUE, warn.conflicts=FALSE)

```
── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.0.0     ✔ purrr   0.2.5
✔ tibble  1.4.2     ✔ dplyr   0.7.6
✔ tidyr   0.8.1     ✔ stringr 1.3.1
✔ readr   1.1.1     ✔ forcats 0.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
```

I think the expected behavior is no output.

**Comment by batpigandme** [comment]
Hmm… I may have spoken too soon (see @hadley's comment in a closed issue, below)
https://github.com/tidyverse/tidyverse/issues/127#issuecomment-384474370

personally, I use 
```r
suppressPackageStartupMessages(library(tidyverse))
```

But, per NEWS:

> You can now suppress this startup message by setting options(tidyverse.quiet = TRUE)

https://github.com/tidyverse/tidyverse/blame/master/NEWS.md#L32-L33

**Comment by tmalsburg** [comment]
Okay, regarding `quietly=TRUE` but what about `warn.conflicts=FALSE`?

**Comment by hadley** [comment]
The conflicts message will go away in the next release since the tidyverse is going to attach conflicted.

The quietly argument `quietly` has much narrower scope than you might think. From the docs:

>  a logical. If TRUE, no message confirming package attaching is printed, and most often, no errors/warnings are printed if package attaching fails.

**Comment by wbvguo** [comment]
Hi, it looks like none of `verbose`/`warn.conflicts`/`quietly` will repress the warning messages for tidyverse 2.0.0. Do we have any plan to fix it?

```r
> library(tidyverse, warn.conflicts = FALSE, verbose = FALSE, quietly = TRUE)

── Attaching core tidyverse packages ───────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     ── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package to force all conflicts to become errors
```

Thanks
