### ISSUE TITLE
tidyverse attaches its children packages at `pos=2`

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/tidyverse#159]
This is not really a bug but this is annoying, at least to me, I would expect it to attach them just before `tidyverse` on the search path.

I don't imagine a situation where someone would want to put `tidyverse` at `pos = 3` and then place the other packages at `pos = 2`. If you believe it would be a less common use case than mine, please consider adapting the behavior.

```
search()
# [1] ".GlobalEnv"        "tools:rstudio"     "package:stats"    
# [4] "package:graphics"  "package:grDevices" "package:utils"    
# [7] "package:datasets"  "package:methods"   "Autoloads"        
# [10] "package:base" 

something <- list()
attach(something)
library(tidyverse,pos = 3)
search()
# [1] ".GlobalEnv"        "package:forcats"   "package:stringr"  
# [4] "package:dplyr"     "package:purrr"     "package:readr"    
# [7] "package:tidyr"     "package:tibble"    "package:ggplot2"  
# [10] "something"         "package:tidyverse" "tools:rstudio"    
# [13] "package:stats"     "package:graphics"  "package:grDevices"
# [16] "package:utils"     "package:datasets"  "package:methods"  
# [19] "Autoloads"         "package:base" 
```

FYI I posted a SO question on how to handle this situation, so your inputs are welcome here or there too! 

https://stackoverflow.com/questions/52892704/how-to-reorder-the-search-path

**Comment by hadley** [comment]
Why does this matter?

**Comment by moodymudskipper** [comment]
In my case I want to evaluate things in the `something` environment, and I want to be able to use `tidyverse` functions in this environment after calling `library(tidyverse, pos = 3)`, which is currently not possible. As for other use cases I think it would matter whenever the `pos` argument is relevant.

**Comment by moodymudskipper** [comment]
Another use case that comes to my mind, that would be more common, is if I want to load `tidyverse` and be sure not to override some other package's functions that I need to makes sure not to break scripts that I wrote without using `::`.

**Comment by hadley** [comment]
This doesn't seem terribly important to me, so I'd recommend simply attaching the packages individually.

**Comment by moodymudskipper** [comment]
This is not possible in my case, I won't decide what packages the user attaches.

In my opinion the fact that attaching packages separately is not equivalent to attaching `tidyverse` is counter intuitive.

Meanwhile I found a fix for my own case and posted it as an answer.

**Comment by hadley** [comment]
Writing code that assumes an environment will be attached in a specific place in the search list is fragile, and seems unlikely to be a productive approach.

**Comment by Steviey** [comment]
+1
