### ISSUE TITLE
More question than issue: structuring a metapackage

### ISSUE THREAD

**Issue by martinamorris** [tidyverse/tidyverse#160]
Hi -- we have a metapackage similar to tidyverse, [statnet](https://github.com/statnet/statnet), which exists only to make it easy to install and load a set of packages for network analysis that share a common data structure and API.  We've been struggling a bit over the years with how to structure it with Depends, Imports, and Suggests -- so I turned to the tidyverse package for guidance (thanks :)

I found myself perplexed by the way the packages are listed in 3 places:  NAMESPACE, DESCRIPTION, and attach.R:

![image](https://user-images.githubusercontent.com/8194530/47282610-c0200480-d594-11e8-880b-e46a5a6b1f00.png)

I'm assuming the orange (DESCRIPTION only) are used by the tidyverse package itself, and aren't intended for the end user.

Attaching the core tidyverse packages with attach.R makes sense (we'd like to copy this).  And it makes sense that you need to Import these in the DESCRIPTION.  But some are also importFrom in NAMESPACE, while others are not.  What is the reason for this difference?

thanks!

**Comment by jennybc** [comment]
I think this is a better fit for the package development section of https://community.rstudio.com/c/package-development. Would you like to take discussion there?

**Comment by martinamorris** [comment]
Sure, thanks (I was in your Seattle WTF workshop btw).

**Comment by jennybc** [comment]
Ah, yes! I remember 🙂

**Comment by batpigandme** [comment]
@maurolepore since Martina opened a thread about this on community, would you mind adding your response there? Closed issues get locked eventually, and, generally, aren't as useful for discussion.

Thanks

https://community.rstudio.com/t/metapackage-structure-best-practices/16852
