### ISSUE TITLE
Rcpp issue when running on HPC cluster

### ISSUE THREAD

**Issue by mikeyEcology** [tidyverse/tidyverse#173]
Hi,
I'm trying to use tidyverse on a HPC cluster and I can install it fine, but when I try to load the library, I get an error about Rcpp that I don't understand. I have tried looking for Rcpp >= 1.0.0, but I can't find it. At the [Rcpp archive page](https://cran.rstudio.com/src/contrib/Archive/Rcpp/) the latest version is 0.12.9. 
Thanks in advance for your suggestions. 

---

Brief description of the problem

```r
library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘Rcpp’ 0.12.16 is already loaded, but >= 1.0.0 is required
```

**Comment by maurolepore** [comment]
This suggests you need to install a newer version of Rcpp. Your current version (I guess the version in stalled on the cluster) is 0.12.16 but you need 1.0.0 or later.

**Comment by mikeyEcology** [comment]
I agree, but if you look at the Rccp page [here](https://cran.rstudio.com/src/contrib/Archive/Rcpp/) there is no version that is 1.0.0 or later, unless I'm missing something?

**Comment by mikeyEcology** [comment]
I found Rcpp 1.0.0 [elsewhere](https://cran.r-project.org/web/packages/Rcpp/index.html). It just wasn't listed on their main version page. Sorry for wasting your time.

**Comment by maurolepore** [comment]
Great! :-)
We are all here to help each other  -- no time wasted at all.
