### ISSUE TITLE
Remove messages when loading tidyverse

### ISSUE THREAD

**Issue by mloop** [tidyverse/tidyverse#174]
When running `library(tidyverse)`, the default behavior is to print the packages loaded and a condensed summary of conflicts. However, particularly for `.Rmd` documents, the most common consequence of this behavior *for the user* is to add `message=FALSE` to the `R` chunk. Therefore, removing the message would decrease the amount of typing required of users. Users wanting the information could still use `tidyverse::tidyverse_conflicts()`.

**Comment by batpigandme** [comment]
Given many users operate outside of Rmd, I think it would be dangerous to suppress all warnings regarding conflicts by default. The tidyverse package neatens this up, but the behaviour is standard for attaching packages in R.

**Comment by jennybc** [comment]
@mloop You might like having a standard "setup chunk", possibly stored as an RStudio snippet, if you use RStudio. And you could put `options(tidyverse.quiet =TRUE)` in it.

**Comment by mloop** [comment]
Thanks for the suggestion @jennybc, and I agree @batpigandme that it is standard output and should not be treated differently. Thanks for the feedback.

**Comment by wlandau** [comment]
Would it be reasonable to implement an environment variable version of `tidyverse.quiet`? I am usually working on several `renv` projects at a time, and it would be nice to edit my `~/.Renviron` once and suppress messages for all of them.
