### ISSUE TITLE
Make a new release of tidyverse

### ISSUE THREAD

**Issue by josegonzalez** [tidyverse/tidyverse#176]
It would be nice to have a new release of tidy verse. The latest release - 1.2.1 - was in November 2017, and having a newer package would be great for versioning :)

**Comment by hadley** [comment]
We don't usually justify releasing new versions based on time alone, but we are planning one in the near future to accompany #111

**Comment by josegonzalez** [comment]
Just a comment, there have been more than a few minor changes since the last.- including bugs and package updates. The request to make a new release wasn't based on the time since the last release, but rather the changes included in that timespan.

Thanks for responding though, much appreciated!
