### ISSUE TITLE
>R-3.5.3 on WIN10 Pro - Error: package or namespace load failed for '...' in rbind(info, getNamespaceInfo(env, "S3methods")): number of columns of matrices must match (see arg 2)

### ISSUE THREAD

**Issue by gwd999** [tidyverse/tidyverse#182]
> 
> 
> Did you reinstall all packages for 3.6, or did you try and use your old R 3.5 packages?

Maybe it was not as clear in the first place - I have absolutey no issues with R-3.6. it is R-3.5. package loading THAT GOT BROKEN! At least for me ... 

One modification I have is that I added the follwoing to my Rprofile.site in order to segreggate the two major version library folders. But I cannnot imagine that this would cause this issue.

```
#adjust .libPaths 
.libPaths( c( paste0("S:/Sdocuments/R/win-library/",R.version$major,".", substring(R.version$minor, 1,1)), .libPaths() ) ) 
```

Further information 

When I switch the R engine (in RStudio) eg to MS R OPEN (which is Version 3.5.2) I get this error message and warning (since my package library is only major version divided 

`Error: package or namespace load failed for ‘ggplot2’ in rbind(info, getNamespaceInfo(env, "S3methods")):
 number of columns of matrices must match (see arg 2)
In addition: Warning message:
package ‘ggplot2’ was built under R version 3.5.3 `

If I switch to R_SERVER (which is based on major version 3.4 and therefore has its own package lib folder)  eg package "ggplot2" runs like a charm. 

_Originally posted by @gwd999 in https://github.com/tidyverse/tidyverse/issues/179#issuecomment-505330136_

**Comment by gwd999** [comment]
I solved it the hard way 
I removed all packages in my 3.5. pkg lib and reinstalled them via 
`p <- as.data.frame(installed.packages(lib.loc = .libPaths()[1]), 
                    stringsAsFactors = FALSE)
head(ip)
str(ip)
path.lib <- unique(ip$LibPath)

# create a vector with all the names of the packages you want to remove
pkgs.to.remove <- ip[,1]
head(pkgs.to.remove)
str(pkgs.to.remove)

sapply(pkgs.to.remove, remove.packages, lib = path.lib)
sapply(pkgs.to.remove, install.packages, lib = path.lib)
`

**Comment by wjcuervob** [comment]
Thank you @gwd999 !!! I was desperate about this issue.
