### ISSUE TITLE
Are older versions of Tinyverse available somewhere?

### ISSUE THREAD

**Issue by rsheppar** [tidyverse/tidyverse#184]
I have an old installation I am supporting. Red Hat 6, GCC 4.9.4.  At run time, we get a  Glibcxx_3.4.21 not found message.  We can not upgrade the OS.  I would like to install an older version that will work with GLIBCXX_3.4.13.  Thanks.
   Ray

[rsheppar@h2 ~]$ strings /usr/lib/libstdc++.so.6.0.13 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH

```

**Comment by hadley** [comment]
You'd need to ask the tinyverse maintainers. This is for tidyverse.
