### ISSUE TITLE
Teach tidyverse about convention for backward incompatible dev version

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyverse#194]
A 9000 in the third component should also be treated as a development version of a package; e.g. 0.8.9000 is a development version that's not backward compatible.

**Comment by jennybc** [comment]
Did you mean to open this here or on usethis?

**Comment by hadley** [comment]
Here and usethis 😬

**Comment by hadley** [comment]
Although now I can't figure out what tidyverse package needs to do here?
