### ISSUE TITLE
Speed of library(tidyverse)

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidyverse#20]
When I load the tidyverse there is a noticeable pause at `Conflicts with tidy packages`. Are there any easy ways to speed that up? As a secondary issue, the timing reported by `system.time()` or profvis (~150ms) is substantially faster than the actual human time that elapses (> 1 sec). Maybe that is neither here nor there.

**Comment by hadley** [comment]
What does `system.time(tidyverse_conflicts())` give for you?

**Comment by hadley** [comment]
BTW it's possible (due to output buffering) the delay is loading all the packages, not printing the conflicts.

**Comment by jennybc** [comment]
``` r
system.time(library(tidyverse))
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats
#>    user  system elapsed 
#>   0.339   0.008   0.348
system.time(tidyverse_conflicts())
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats
#>    user  system elapsed 
#>   0.015   0.000   0.015
```

I guess it is the loading? It is not taking >1 seconds for me to load the tidyverse right now FWIW. The above is quite repeatable and matches my perception too.

**Comment by hadley** [comment]
Ok, I'm going to close for now. Feel free to ping if it happens again.
