### ISSUE TITLE
Paper not published?

### ISSUE THREAD

**Issue by msberends** [tidyverse/tidyverse#208]
I would love to cite you in our next paper which is basically submission ready, with the citation as defined in tidyverse 1.3.0 that is now on CRAN. Will the DOI soon become valid as far as you know? Because now:

```r
citation("tidyverse")
#>  Wickham et al., (2019). Welcome to the tidyverse. Journal of Open Source Software, 4(43), 1686,
#>  https://doi.org/10.21105/joss.01686
```

Does not exist:

![image](https://user-images.githubusercontent.com/31037261/69327124-46ea5980-0c4d-11ea-8029-861f67f547a3.png)

**Comment by msberends** [comment]
Never mind, I now see it is not yet accepted: https://joss.theoj.org/papers/3457fa44beec99c5585e1edb601cee61

Then it was perhaps not the best communication in NEWS and nor to submit it already to CRAN :wink:

**Comment by batpigandme** [comment]
> nor to submit it already to CRAN 😉

It's a chicken-egg problem. The paper gets pegged to a release number, which needs to be on CRAN. (If you scroll to the end of this, you'll see the delicate dance: https://github.com/openjournals/joss-reviews/issues/1686 )

**Comment by msberends** [comment]
👍 All good!
