### ISSUE TITLE
reconcile tidyverse with rstudio code introspection

### ISSUE THREAD

**Issue by dpastoor** [tidyverse/tidyverse#21]
I will also submit a bug report to rstudio, but figured it might be reasonable to track here, feel free to close if not. When using tidyverse, the associated functions are not picked up (Rstudio 1.0.44) so get linting warnings all over the place like so:

![image](https://cloud.githubusercontent.com/assets/3196313/20113047/bb88a9fe-a5bc-11e6-88f4-b29b3785d136.png)

pinging @kevinushey and @jjallaire

**Comment by dpastoor** [comment]
linting warning is `no symbol named 'as_data_frame'` etc.

**Comment by kevinushey** [comment]
Thanks for the bug report. I'm guessing the `tidyverse` package has not yet been loaded in your case? Explicitly loading the package (ie, executing the `library(tidyverse)` call) should be a workaround in the interim.

We'll take a look, thanks!

**Comment by dpastoor** [comment]
thanks kevin, actually this error persists when tidyverse is loaded.

![image](https://cloud.githubusercontent.com/assets/3196313/20115416/3079d6e4-a5c6-11e6-9e69-94973056d1e1.png)

Occurs in both Rmd and R files

**Comment by kevinushey** [comment]
After loading the package, did you try re-saving the document (so that diagnostics are re-generated)? I was not able to reproduce the issue on my OS X machine, so I think we'll need some more details (`devtools::session_info()`?)

**Comment by dpastoor** [comment]
I'm undergoing the Sierra update on my MBP, so am on windows for the moment.

Restarting did not resolve issue:

![image](https://cloud.githubusercontent.com/assets/3196313/20115547/a8ba88e2-a5c6-11e6-848e-8351e92487a4.png)

```
Packages -----------------------------------------------------------------------------------------------------
 package    * version    date       source                         
 assertthat   0.1        2013-12-06 CRAN (R 3.3.2)                 
 colorspace   1.2-7      2016-10-11 CRAN (R 3.3.2)                 
 DBI          0.5-1      2016-09-10 CRAN (R 3.3.2)                 
 devtools     1.12.0     2016-06-24 CRAN (R 3.3.2)                 
 digest       0.6.10     2016-08-02 CRAN (R 3.3.2)                 
 dplyr      * 0.5.0      2016-06-24 CRAN (R 3.3.2)                 
 ggplot2    * 2.1.0.9001 2016-11-07 Github (hadley/ggplot2@70c3d69)
 gtable       0.2.0      2016-02-26 CRAN (R 3.3.2)                 
 lazyeval     0.2.0      2016-06-12 CRAN (R 3.3.2)                 
 magrittr     1.5        2014-11-22 CRAN (R 3.3.2)                 
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.2)                 
 munsell      0.4.3      2016-02-13 CRAN (R 3.3.2)                 
 plyr         1.8.4      2016-06-08 CRAN (R 3.3.2)                 
 purrr      * 0.2.2      2016-06-18 CRAN (R 3.3.2)                 
 R6           2.2.0      2016-10-05 CRAN (R 3.3.2)                 
 Rcpp         0.12.7     2016-09-05 CRAN (R 3.3.2)                 
 readr      * 1.0.0      2016-08-03 CRAN (R 3.3.2)                 
 scales       0.4.0.9003 2016-11-07 Github (hadley/scales@d58d83a) 
 tibble     * 1.2        2016-08-26 CRAN (R 3.3.2)                 
 tidyr      * 0.6.0      2016-08-12 CRAN (R 3.3.2)                 
 tidyverse  * 1.0.0      2016-09-09 CRAN (R 3.3.2)                 
 withr        1.0.2      2016-06-20 CRAN (R 3.3.2) 
```

**Comment by dpastoor** [comment]
woops clipped it off:

```
Session info -------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-11-08                  
```

Windows 10 with all recent patches

**Comment by kevinushey** [comment]
I can't reproduce on a Windows 7 VM. Here's what I did with the following text:

```
library(tidyverse)
mtcars %>%
	as_data_frame() %>%
	mutate(cyl2 = cyl ^ 2)
```

1. Copy the contents to a file, `hello.R`.
2. Save the file. Note that diagnostics are generated (this is a bug).
3. Execute the `library(tidyverse)` call.
4. Re-save the file. Diagnostics are now appropriately cleared, as all the symbols (`as_data_frame` etc.) are now discovered on the search path.

Do you still see diagnostics persist even after step 4?

**Comment by dpastoor** [comment]
ok VERY odd behavior

![image](https://cloud.githubusercontent.com/assets/3196313/20115883/ffb4c0da-a5c7-11e6-9e00-eec467b8e190.png)

Here's where it gets really weird - if I save it out of the scope of the project (eg to my desktop) 

![image](https://cloud.githubusercontent.com/assets/3196313/20115916/1d145bb8-a5c8-11e6-8622-21e0d8d929f7.png)

poof the errors go away (still keeping the overall R project open)

**Comment by dpastoor** [comment]
If you want to look around with the Rbuild/gitignore/rproj files, the project from which it is happening is

https://github.com/dpastoor/bayesiantutorial

If you'd like I can grab another windows machine and see what happens?

**Comment by kevinushey** [comment]
Okay, that makes more sense -- the mechanism that RStudio uses for looking up symbols differs for R packages. You don't want to import the `tidyverse` package in an attempt to make the symbols from the tidyverse available for your package; you should instead explicitly import the package namespaces / symbols you use.

**Comment by dpastoor** [comment]
Ah I see, is there a way to tell Rstudio to ignore it's "package" nature? I just use the description file as a less rigorous version of packrat to approximately keep track of dependencies required for a project, so someone else can pull in the dependencies by installing the "package" from the description file.

**Comment by kevinushey** [comment]
If you remove the `Type: package` entry from the `DESCRIPTION` file, that would help -- otherwise I don't think there's any other mechanism currently.

**Comment by dpastoor** [comment]
Thanks,

gave that a shot and no dice for now. If I find any other workarounds I'll update the issue. Thanks for your help digging around with it.
