### ISSUE TITLE
Add dtplyr?

### ISSUE THREAD

**Issue by boshek** [tidyverse/tidyverse#216]
Current the tidyverse package does not include `dtplyr` (which is fun an awesome and amazing effort):

``` r
packageVersion('tidyverse')
#> [1] '1.3.0'

tidyverse::tidyverse_packages()
#>  [1] "broom"      "cli"        "crayon"     "dbplyr"     "dplyr"     
#>  [6] "forcats"    "ggplot2"    "haven"      "hms"        "httr"      
#> [11] "jsonlite"   "lubridate"  "magrittr"   "modelr"     "pillar"    
#> [16] "purrr"      "readr"      "readxl"     "reprex"     "rlang"     
#> [21] "rstudioapi" "rvest"      "stringr"    "tibble"     "tidyr"     
#> [26] "xml2"       "tidyverse"
```

<sup>Created on 2019-12-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I am wondering if you'd consider a PR adding `dtplyr` as a non-core tidyverse package. I was expecting `dtplyr` to be updated with `tidyverse::tidyverse_update`

**Comment by jtelleriar** [comment]
Agree.

dtplyr is a strong candidate to be added to the tidyverse!
