### ISSUE TITLE
tidyverse x stats files - filter() and lag ()

### ISSUE THREAD

**Issue by cesar-massaro** [tidyverse/tidyverse#224]
install.packages("tidyverse")
library("tidyverse")
-- Attaching packages --------------------------------------- tidyverse 1.3.0 --
v ggplot2 3.3.0     v purrr   0.3.3
v tibble  2.1.3     v dplyr   0.8.5
v tidyr   1.0.2     v stringr 1.4.0
v readr   1.3.1     v forcats 0.5.0
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()

**Comment by batpigandme** [comment]
This is known, and the warning is to remind you that this is the case. To use the stats versions, you can prefix with `stats::`, or see the conflicted package. https://github.com/r-lib/conflicted
