### ISSUE TITLE
Rtools dependency

### ISSUE THREAD

**Issue by ahcyip** [tidyverse/tidyverse#226]
I recently installed R and RStudio on a new computer. The first thing I did was install.packages("tidyverse") but this failed with error message indicating I needed Rtools, which I could not install within RStudio. I think I eventually manually looked up Rtools and downloaded it and installed it. 

I didn't see any notes or documentation about this. If this is an unavoidable issue and generalizes to all computers/installs, could documentation be added to indicate when/where/how to install Rtools?

P.S. why not have tidyverse get automatically installed in RStudio installations? :)

**Comment by batpigandme** [comment]
Rtools should only be necessary when you build from source (which is true for all packages, see [info here](https://rstats.wtf/set-up-an-r-dev-environment.html#windows-system-prep)). Did you encounter something to the effect of `Do you want to install from sources the packages which need compilation?`?

**Comment by ahcyip** [comment]
I think I did select yes (I did this a month ago). Thanks for the link to the "what they forgot" reference :)
