### ISSUE TITLE
Feature request: A package that contains base error classes similar to python's built in exceptions.

### ISSUE THREAD

**Issue by s-fleck** [tidyverse/tidyverse#228]
I am note sure if this is the right place to ask.

Some packages in the tidyverse are starting to throw error conditions with proper S3 classes, but very few other R packages do this. It would be nice to have base error classes along with guidance on when they should be used, like the [built-in exceptions](https://docs.python.org/3/library/exceptions.html) of python. Arguably, this is something that should be provided by base R, but the chances for that are slim in the near future. I was wondering if the tidyverse could provide something like this as a package.

**Comment by batpigandme** [comment]
Hi @s-fleck, we really only use issues here if there's something wrong with the wrapper package. Could you file issue(s) in the package repo that's throwing the error(s) if it's not already covered by another issue? It may be vctrs. The best way to check is by running a backtrace. Also, a MRE/reprex is always a help. Thanks.
