### ISSUE TITLE
Include rio into tidyverse

### ISSUE THREAD

**Issue by sda030** [tidyverse/tidyverse#232]
Based on tidyverse's own list of packages for [importing/exporting files](https://www.tidyverse.org/packages/#import), I think it is pretty clear that the R environment lacks an intuitive way of import/export of files, in particular for the beginner. Having to know which package, and also the exact function name for a particular file type, and then all the various forms for argument names is unnecessary. The [`rio`-package](https://github.com/leeper/rio) is the equivalent of the broom-package for files by using a single function (`import()`/`export()`) across all data files. It is very intuitive, follows tidyverse-philosophy, allows returning tibbles, and makes it a breeze to work with files. I do not understand why this is seemingly kept out in the cold. (I am not a rio-developer so I have no personal interests to disclose). 
So why bother? Locating it among other tidyverse packages will attract users and developers, and set certain expectations for the upstream package developers in the same way as broom sets expectations about what kind of functions all model-objects should return.
If you let me going on a relevant rant: I sometimes think that the R-community's perhaps biggest weakness is that there are generally extrinsic and intrinsic incentives to start packages, but rarely any incentives for contributing to existing packages. (Try applying for funding from a research agency for _contributing_ to a package that lacks helpers, rather than starting something new). Although a certain level of competition and free choice is useful, it can actually hinder growth if people just see chaos.

**Comment by hadley** [comment]
rio doesn't really implement data import/export, it just provides a convenient central wrapper around many different packages. This makes it complementary to the tidyverse, and not something I think makes sense to include within the tidyverse. 

Not being included in the tidyverse does not imply being "left out in the cold".
