### ISSUE TITLE
Relicense as MIT

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyverse#235]
I have reviewed all non-RStudio [contributors](https://github.com/tidyverse/tidyverse/graphs/contributors).  I think there are only two contributions significant enough to merit a potential copyright claim:

* [x] https://github.com/tidyverse/tidyverse/commit/2b5330e9bbe5feaa362885a0ff35cac9c6b82531 by @dchiu911 
*  [x] https://github.com/tidyverse/tidyverse/commit/264273d73526392c6a022598809be20ef51686ee by @zkamvar

@dchiu911, @zkamvar would consider giving your permission to relicense tidyverse as MIT? If so, please comment "I agree" below

**Comment by zkamvar** [comment]
I agree

**Comment by dchiu911** [comment]
I agree

**Comment by hadley** [comment]
Thank you!
