### ISSUE TITLE
feather installation failed with "big endian" issue

### ISSUE THREAD

**Issue by bergen288** [tidyverse/tidyverse#236]
I am trying to install R packages on AIX7.2 server.  My feather installation failed with following error.  According to my google search, this issue should have been fixed long time ago: https://github.com/tidyverse/tidyverse/issues/36.  My version is feather_0.3.5.tar.gz.  Can someone please tell me how to fix it?

```r
* installing *source* package 'feather' ...
** package 'feather' successfully unpacked and MD5 sums checked
** using staged installation
Platform is big endian. This is currently unsupported.
ERROR: configuration failed for package 'feather'
* removing '/software/R/site-library/feather'
```

**Comment by batpigandme** [comment]
Could you please file an issue in the feather repo? Since the tidyverse just wraps the component packages, we try to resolve issues for individual packages in their respective repos. Thanks.
https://github.com/wesm/feather/issues
