### ISSUE TITLE
Tidyverse not recognising spatial objects, simple features, after update

### ISSUE THREAD

**Issue by Molly-Scott** [tidyverse/tidyverse#237]
I had to reset my computer and this meant upgrading R(4.0), R Studio(1.3.959) and Rtools(40) to the latest versions. In doing so, code that worked perfectly using tidyverse and mapview, and ggmap to create maps no longer work, i.e. R Studio no longer recognises spatial features, simple features, geometry, coordinate reference systems etc. I think it may be something to do with tidyverse because  I have noticed that when I do not use the summarise() function to create a new dataframe the code works see below:

#dataframe of positions 

df.work <- data.frame(Tag.ID=c(7917,7917, 7917,7918,7918,7918,7919,7919,7919),
                 Station.Name=c("FAD X", "FAD U", "FAD L", "GR5","Reef44", "Kbay", "HIMB", "R8", "R9"),
                 Num.Det=c(1, 5, 6, 5, 7, 90, 7, 55, 32),
                 Longitude=c(-157.9933, -157.8279, -157.7838, -158.1492, -157.8197, -157.7916, -157.7659, -157.7745, -157.7793),
                 Latitude=c(21.86333, 21.49908, 21.43453, 21.62387, 21.46288, 21.44778, 21.50943,  21.4972, 21.48997))

#transform to sf
df_sf.work <- 
  df.work %>%  ##  Calculate number of detections per station per tag
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)

#map
df_map <-
  ggmap(myMap) +
  coord_sf() +
  geom_sf(data = df_sf.work, aes(size = Num.Det, color = factor(Tag.ID), fill = factor(Tag.ID)), shape=21, inherit.aes = F) +
  labs(x = "Longitude", y = "Latitude", color = "Tag ID", fill = "Tag ID", size = "Number of detections") +
  facet_wrap(~Tag.ID)                 

df_map                 
              
# with mapview
sf_mapview <- 
  df_sf.work %>% 
  mapview(color = "white", alpha.region = 0, cex = 3, legend = F, homebutton = F, layer = "Station.Name", map.types = "Esri.WorldImagery")

sf_mapview

df_mapview <-
  (sf_mapview +
     mapview(df_sf, zcol = "Tag.ID", cex = "Num.Det", burst = T, legend = F, homebutton = F))@map 

df_mapview

But when I create a new dataframe using summarise() and try to add it to a map, I get the following errors: 

#create map

```{r}

myLocation = c(-158.287, 21.21425, -157.676, 21.7337)
myMap = get_map(location=myLocation, source="google", maptype = "satellite")
ggmap(myMap)           


#dataframe of positions (combdata)


df <- data.frame(Tag.ID=c(7917,7917, 7917,7918,7918,7918,7919,7919,7919),
                 Station.Name=c("FAD X", "FAD U", "FAD L", "GR5","Reef44", "Kbay", "HIMB", "R8", "R9"),
                 Longitude=c(-157.9933, -157.8279, -157.7838, -158.1492, -157.8197, -157.7916, -157.7659, -157.7745, -157.7793),
                 Latitude=c(21.86333, 21.49908, 21.43453, 21.62387, 21.46288, 21.44778, 21.50943,  21.4972, 21.48997))
#
 
#create new df with new column NumDet using summarise() and transform to sf

df_sf <- 
  df %>% 
  group_by(Tag.ID, Station.Name, Longitude, Latitude) %>% 
  dplyr::summarise(Num.Det = n()) %>%  ##  Calculate number of detections per station per tag
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)


df_map <-
  ggmap(myMap) +
  coord_sf() +
  geom_sf(data = df_sf, aes(size = Num.Det, color = factor(Tag.ID), fill = factor(Tag.ID)), shape=21, inherit.aes = F) +
  labs(x = "Longitude", y = "Latitude", color = "Tag ID", fill = "Tag ID", size = "Number of detections") +
  facet_wrap(~Tag.ID)                 

df_map                 
 Error: stat_sf requires the following missing aesthetics: geometry            
# with mapview

sf_mapview <- 
  df_sf %>% 
  mapview(color = "white", alpha.region = 0, cex = 3, legend = F, homebutton = F, layer = "Station.Name", map.types = "Esri.WorldImagery")

sf_mapview

df_mapview <-
  (sf_mapview +
     mapview(df_sf, zcol = "Tag.ID", cex = "Num.Det", burst = T, legend = F, homebutton = F))@map 

df_mapview

Error:  oops! Arguments xcol and/or ycol are missing! You probably expected df to be a spatial object. However it is of class grouped_df. 

Any ideas to help me get over this issue?

**Comment by Molly-Scott** [comment]
Hi there, just to let you know - I re-installed the previous version of dplyr and now everything is working again. I think this is a bug with the recent dplyr update.

PackageUrl <- "https://cran.r-project.org/src/contrib/Archive/dplyr/dplyr_0.8.5.tar.gz"
install.packages(PackageUrl, repos=NULL, type="source")

**Comment by courtiol** [comment]
@Molly-Scott, this is the wrong place to post an issue about that.

Here is the package for the tidyverse **package**.

If the package sf has difficulty handling the new version dplyr, you should post the issue here: https://github.com/r-spatial/sf/issues

If it turns out it is a problem in dplyr, the developers of sf will leave an issue on the GitHub page for dplyr.
