### ISSUE TITLE
problem with load tidyverse in R4.0.2

### ISSUE THREAD

**Issue by HerClau** [tidyverse/tidyverse#238]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

```r
library(tidyverse)
Registered S3 methods overwritten by 'broom':
  method             from
  augment.rowwise_df     
  augment.tbl_df         
  glance.rowwise_df      
  glance.tbl_df          
  tidy.rowwise_df        
  tidy.tbl_df            
Error: package or namespace load failed for ‘tidyverse’:
 .onLoad failed in loadNamespace() for 'broom', details:
  call: loadNamespace(name)
  error: there is no package called ‘backports’
```

**Comment by courtiol** [comment]
@HerClau, you probably have had a problem during the installation of broom or during an update of R.
To solve this issue, just reinstall broom:
```r
install.packages("broom")
```
and everything should be back in order.

As far as I can see there is no issue in tidyverse itself: in the DESCRIPTION files, tidyverse does list its dependence to broom in Imports.
The DESCRIPTION file from broom seems fine to: it does list its dependence to backports in Imports.
