### ISSUE TITLE
Question about installing 'tidyverse' from GitHub

### ISSUE THREAD

**Issue by steveb-cirina** [tidyverse/tidyverse#24]
When installing `tidyverse` from GitHub, do the other packages (`dplyr`, `tidyr`, etc.) get installed from GitHub as well or from CRAN ?  Each method may be desirable at different times.

Thanks.

**Comment by hadley** [comment]
They are installed from CRAN

**Comment by steveb-cirina** [comment]
I like to use the development version of `dplyr`, if I install `tidyverse` will it try to replace it with the CRAN version ?  Also, will other packages be automatically updated ?

**Comment by hadley** [comment]
No
