### ISSUE TITLE
Add tidyselect and other packages?

### ISSUE THREAD

**Issue by courtiol** [tidyverse/tidyverse#241]
I wonder if you would be OK for having tidyselect as part of the package list.

This could be PR together with #216 & #229...

But perhaps it should be first decided whether or not other packages would also need to be included in the list.
E.g. if {rlang} stays in, perhaps {vctrs} should be included too.

**Comment by courtiol** [comment]
Related to that, purrr looks a bit like an odd ball compared to the 7 other core packages.
I think that these days, `dplyr::across()` and `dplyr::c_across()` will probably replace calls to mapping functions and I am not sure users rely on purrr for much else.
So, if you wanted to keep the core packages as those focussed on basic data manipulation, perhaps purrr should no longer be included within the list of core packages.

**Comment by hadley** [comment]
tidyselect isn't a user facing package so doesn't need to be included.
