### ISSUE TITLE
What version of dplyr is required?

### ISSUE THREAD

**Issue by davidd147** [tidyverse/tidyverse#245]
I am seeing an issue whereby I need to update my version of dplyr but the documentation says 0.8.3 above is supported
https://cran.r-project.org/web/packages/tidyverse/index.html

![image](https://user-images.githubusercontent.com/5174247/95928289-d6bd5880-0d75-11eb-9e31-e0a44b75a9d1.png)

Error
Loading required package: tidyverse
Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘dplyr’ 0.8.3 is already loaded, but >= 1.0.0 is required

Did something change recently? Any help would be appreciated.

**Comment by batpigandme** [comment]
> namespace ‘dplyr’ 0.8.3 is already loaded

This means that you're in an R session that already has dplyr attached. Are you in a fresh R session?

**Comment by davidd147** [comment]
But is it possible to to use dplyr 0.8.3? or do I need to upgrade.
