### ISSUE TITLE
problem with dplyr::filter 

### ISSUE THREAD

**Issue by JLYJabc** [tidyverse/tidyverse#247]
I have a df of timestamps and of ids. There are multiple timestamps pr Id, 

I want to filter the df by a date and then keep one unique ID.

However, I get the wrong results when I put the two requirements into the same filter compared with if I pipe the result into a new filter()

The result is sometimes the same so I have made a loop to run the comparisson 500 times. I find that the result is only identical about 100 times out of 500. (i'm struggeling to get consistent results with set.seed, so I used this quirky approach).

I'm running dplyr 1.0.2 with R: 4.0.2

I guess that the result should be the same always?

```r
num <- 1000
count <- 0
for(i in 1:500){

library(magrittr)
x <- tibble::tibble(
  id = LETTERS[rbinom(num, 25, 0.50)+1],
  timestamp = Sys.Date() - rbinom(num, 180, 0.50))

x1 <- x %>% 
  dplyr::filter(
    timestamp < as.Date("2020-08-01"),
    !duplicated(id))

x2 <- x %>% 
  dplyr::filter(
    timestamp < as.Date("2020-08-01")) %>% 
  dplyr::filter(
    !duplicated(id))

if(isTRUE(dplyr::all_equal(x1, x2))) count <- count+1

}
```

**Comment by batpigandme** [comment]
tidyverse is a meta package that wraps the individual packages. We track issues with those packages (in this case, dplyr) in their respective repos. Could you please file this there?
Thanks
