### ISSUE TITLE
Tidyverse on Apple Silicon Macs

### ISSUE THREAD

**Issue by tzakharko** [tidyverse/tidyverse#248]
I would like to open this issue as a "bird's eye" overview of the current state of the Tidyverse building and running natively on Apple Silicon Macs. I hope this is the right place to do it, as I am not aware of any other communication channels for this kind of meta-discussion. 

First of all: good news! Once [`testthat` is patched](https://github.com/r-lib/testthat/pull/1246), all the Tidyverse packages, including their dependencies, build and installs without errors with a native Aarch64 build of R 4.0.3. In the  end, it might "just work". 

Is there a way how I can easily run tests for all the packages or do I have to invoke `testthat` manually with each package source separately?

**Comment by psobolewskiPhD** [comment]
I have an M1 MacBook Pro (Big Sur 11.1)
Installed R (native) via homebrew:
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: arm-apple-darwin20.2.0 (64-bit)
Running under: macOS  11.1

Matrix products: default
BLAS:   /opt/homebrew/Cellar/r/4.0.3_1/lib/R/lib/libRblas.dylib
LAPACK: /opt/homebrew/Cellar/r/4.0.3_1/lib/R/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3

Installed gfortran11 from
https://github.com/fxcoudert/gfortran-for-macOS/releases

Installed devtools from source
install.packages("devtools", type="source")
Warning messages:
1: In install.packages("devtools", type = "source") :
  installation of package ‘gert’ had non-zero exit status
2: In install.packages("devtools", type = "source") :
  installation of package ‘usethis’ had non-zero exit status
3: In install.packages("devtools", type = "source") :
  installation of package ‘devtools’ had non-zero exit status

gert config error, needs libgit2
brew install libgit2
install.packages(“gert”, type=“source”)
>success
usethis: gert dependency
install.packages(“usethis”, type=“source”)

Then reran
install.packages("devtools", type="source")
library(devtools)
>success

> devtools::has_devel()
Your system is ready to build packages!

install.packages(“tidyverse”, type="source")
>success
> library(tidyverse)
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.3.2     ✔ purrr   0.3.4
✔ tibble  3.0.4     ✔ dplyr   1.0.2
✔ tidyr   1.1.2     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

**Comment by MeiDongstat** [comment]
> I have an M1 MacBook Pro (Big Sur 11.1)
> Installed R (native) via homebrew:
> 
> > sessionInfo()
> > R version 4.0.3 (2020-10-10)
> > Platform: arm-apple-darwin20.2.0 (64-bit)
> > Running under: macOS  11.1
> 
> Matrix products: default
> BLAS: /opt/homebrew/Cellar/r/4.0.3_1/lib/R/lib/libRblas.dylib
> LAPACK: /opt/homebrew/Cellar/r/4.0.3_1/lib/R/lib/libRlapack.dylib
> 
> Random number generation:
> RNG: Mersenne-Twister
> Normal: Inversion
> Sample: Rounding
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats graphics grDevices utils datasets methods base
> 
> loaded via a namespace (and not attached):
> [1] compiler_4.0.3
> 
> Installed gfortran11 from
> https://github.com/fxcoudert/gfortran-for-macOS/releases
> 
> Installed devtools from source
> install.packages("devtools", type="source")
> Warning messages:
> 1: In install.packages("devtools", type = "source") :
> installation of package ‘gert’ had non-zero exit status
> 2: In install.packages("devtools", type = "source") :
> installation of package ‘usethis’ had non-zero exit status
> 3: In install.packages("devtools", type = "source") :
> installation of package ‘devtools’ had non-zero exit status
> 
> gert config error, needs libgit2
> brew install libgit2
> install.packages(“gert”, type=“source”)
> 
> > success
> > usethis: gert dependency
> > install.packages(“usethis”, type=“source”)
> 
> Then reran
> install.packages("devtools", type="source")
> library(devtools)
> 
> > success
> 
> > devtools::has_devel()
> > Your system is ready to build packages!
> 
> install.packages(“tidyverse”, type="source")
> 
> > success
> > library(tidyverse)
> > ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
> > ✔ ggplot2 3.3.2     ✔ purrr   0.3.4
> > ✔ tibble  3.0.4     ✔ dplyr   1.0.2
> > ✔ tidyr   1.1.2     ✔ stringr 1.4.0
> > ✔ readr   1.4.0     ✔ forcats 0.5.0
> > ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
> > ✖ dplyr::filter() masks stats::filter()
> > ✖ dplyr::lag()    masks stats::lag()

Hi, did you have the issue solved?

**Comment by MeiDongstat** [comment]
> > Hi, did you have the issue solved?
> 
> I've not changed anything in my setup, works just as described above.
> I've been running everything native on my M1 since that day—Dec. 28, 2020, using native R and native VS Code.
> Just installed all my packages from source.

Thank you. I have gfortran and libgit2 installed but am still unable to install devtools. SessionInfo below:
R Under development (unstable) (2021-08-07 r80721)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Big Sur 11.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.0 tools_4.2.0   

Did you make any other changes?

**Comment by psobolewskiPhD** [comment]
No, what I posted above is everything I had to do. I've been using that R environment ever since. Actually I'm still on 4.03 'cause I've been lazy and busy with other things.
Can you post what you're trying and what error/warnings you're getting?

**Comment by MeiDongstat** [comment]
I'm trying to install "devtools". And I got the following error:

<stdin>:1:10: fatal error: 'git2.h' file not found
#include <git2.h>
         ^~~~~~~~
1 error generated.
----------------------------------------------------------------------
ERROR: configuration failed for package ‘gert’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/gert’
Warning in install.packages :
  installation of package ‘gert’ had non-zero exit status

**Comment by psobolewskiPhD** [comment]
I suspect this is a path issue.
In my case both R and libgit2 were installed via homebrew, so I guess everything was peachy.
Looks like you're using CRAN R in the conventional location, so it could be related to that.
BTW, is installing from source even needed now? I'd assume with an official R being osx-arm64 that many/most packages binaries are also osx-arm64 or universal? See:
https://cran.r-project.org/web/checks/check_summary_by_package.html#summary_by_package

**Comment by MeiDongstat** [comment]
I uninstalled R and reinstall it using brew and now is working!! Thank you so much.

Installing from source is still needed now based on my experience.

**Comment by hadley** [comment]
Everything appears to be working now: https://cran.r-project.org/web/checks/check_results_tidyverse.html

**Comment by danbachar** [comment]
what worked for me was:
`brew install libtiff agg fontconfig fribidi harfbuzz`
then on R Studio:
`install.packages("textshaping", type="source")`
`install.packages("pkgdown", type="source")`
`install.packages("devtools", type="source")`
`install.packages("tidyverse", type="source")`
