### ISSUE TITLE
Dates, inequalities and infinite values printing as NA. 

### ISSUE THREAD

**Issue by davidaarmstrong** [tidyverse/tidyverse#249]
I've got a question about the intended behavior of printing dates that were created through inequalities.  For example, I create some data here such that the variable `date` is a date with one missing value and I create `date2` such that it is the minimum value of `date` when `x` is bigger than 3.  There are no such instances in the first value of `group` in the data and the warning is printed that `Inf` is being returned as a result, which seems reasonable enough.  However, in the example below, you can see that these dates that were returned as `Inf` print as `NA` just as the original `NA` date did.  Further, these printed `NA` values don't evaluate to `TRUE` when `is.na()` is invoked.  Is this intended, or is there a way to have them print as `Inf` in the output? 

```{r}
tib <- tibble::tibble(
  x = c(1,2,3,4,5,6), 
  date = lubridate::as_date(c("1994-04-01", "1994-04-02",
                              "1994-04-01", "1994-04-02",
                              "1994-04-01", NA)), 
  group = c(1,1,2,2,3,3))
tib <- tib %>% 
  group_by(group) %>% 
  mutate(date2 = min(date[which(x > 3)], na.rm=TRUE))
# Warning messages:
# 1: Problem with `mutate()` input `date2`.
# ℹ no non-missing arguments to min; returning Inf
# ℹ Input `date2` is `min(date[which(x > 3)], na.rm = TRUE)`.
# ℹ The error occurred in group 1: group = 1. 
# 2: In min.default(numeric(0), na.rm = TRUE) :
#   no non-missing arguments to min; returning Inf

tib
# # A tibble: 6 x 4
# # Groups:   group [3]
#         x date       group date2     
#     <dbl> <date>     <dbl> <date>    
# 1     1 1994-04-01     1 NA        
# 2     2 1994-04-02     1 NA        
# 3     3 1994-04-01     2 1994-04-02
# 4     4 1994-04-02     2 1994-04-02
# 5     5 1994-04-01     3 1994-04-01
# 6     6 NA             3 1994-04-01

is.na(tib$date)
# [1] FALSE FALSE FALSE FALSE FALSE  TRUE
is.na(tib$date2)
# [1] FALSE FALSE FALSE FALSE FALSE FALSE
```

**Comment by batpigandme** [comment]
tidyverse is a meta package that wraps the individual packages. We track issues with those packages (in this case, tibble) in their respective repos. Could you please file this there?
Thanks

**Comment by davidaarmstrong** [comment]
Sure, thanks.
