### ISSUE TITLE
No summary function supplied, defaulting to `mean_se()`

### ISSUE THREAD

**Issue by AIverson92** [tidyverse/tidyverse#250]
ggplot(diamonds) + 
  stat_summary(aes(cut, depth)) 
               fun.min = min 
               fun.max = max
               fun =mean

**Comment by batpigandme** [comment]
The tidyverse package is a wrapper around individual packages, and we track issues and feature requests for the packages in their individual repos. So, please file this in the repo for the appropriate package (I can't quite tell without a full reprex—see below for details).

Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks
