### ISSUE TITLE
#> Error in ggplot(diamonds): 

### ISSUE THREAD

**Issue by AIverson92** [tidyverse/tidyverse#252]
library(reprex)
data("diamonds")
#> Warning in data("diamonds"): data set 'diamonds' not found
ggplot(diamonds) + 
  stat_summary(aes(cut, depth)) 
#> Error in ggplot(diamonds): 
fun.min = min
fun.max = max
fun =median

**Comment by batpigandme** [comment]
Please see my previous responses re. filling in individual package repos. Thank you.
