### ISSUE TITLE
Document system dependencies

### ISSUE THREAD

**Issue by fxedel** [tidyverse/tidyverse#253]
## Short summary

Document system dependencies like curl or openssl and how to install to them, so especially new users can install them right before installing tidyverse, which makes the whole installation process easier.

## Problem description

When installing tidyverse, some system dependencies like curl or openssl are needed. If these are not installed, the tidyverse installation process fails:

```
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
```

or

```
--------------------------- [ANTICONF] --------------------------------
Configuration failed because openssl was not found. Try installing:
 * deb: libssl-dev (Debian, Ubuntu, etc)
 * rpm: openssl-devel (Fedora, CentOS, RHEL)
 * csw: libssl_dev (Solaris)
 * brew: openssl@1.1 (Mac OSX)
If openssl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...
```

Users may be confused with these errors (see #225) and even if they understand what to do, the installation process is split into several parts as you have to install the needed packages (e.g. via APT) and then continue the tidyverse installation.

## Suggested change

Document the installation of needed system dependencies, e.g.:

```
apt install libcurl4-openssl-dev libssl-dev # ... maybe more? maybe libxml2-dev, see #243
```

Of course, installation with rpm, csw and brew should also be documented.

**Comment by hadley** [comment]
Probably best just to document `pak::pkg_system_requirements("tidyverse")` which will tell you this.

**Comment by CraterDylan** [comment]
I tried to install pak first, as suggested, but it also fails for the same reason (libcurl missing)! I would still like a better documentation for linux (maybe [here](https://tidyverse.tidyverse.org/)) because the issue is widespread but the solution isn't.
