### ISSUE TITLE
Rownames

### ISSUE THREAD

**Issue by rskl92** [tidyverse/tidyverse#261]
Hello,

I had code that had worked for many datasets that I had been using for the past year. Today, it is reporting the following message.
Error: `.data` must be a data frame without row names.
RError: `.data` must be a data frame without row names

My dataset does not have rownames.

Can you advise please?
TIA

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

Once we whittle things down on community, we can figure out what package is causing problems, and then, if it's a bug, open an issue in that specific repository.
