### ISSUE TITLE
R packages installation error : Error in eval(exprs[i], envir) : object 'confint.default' not found

### ISSUE THREAD

**Issue by englianhu** [tidyverse/tidyverse#267]
https://www.reddit.com/r/RStudio/comments/ojyntu/r_packages_installation_error/

Unable install or update any R packages... Kindly assist

```r
> devtools::install_github("tidyverse/tidyverse")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo tidyverse/tidyverse@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                            
2: CRAN packages only             
3: None                           
4: stringi (1.6.2 -> 1.7.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 4
stringi (1.6.2 -> 1.7.2) [CRAN]
Rcpp    (NA    -> 1.0.7) [CRAN]
isoband (NA    -> 0.2.5) [CRAN]
Installing 3 packages: stringi, Rcpp, isoband
Installing packages into ‘/usr/lib/R/library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/stringi_1.7.2.tar.gz'
Content type 'application/x-gzip' length 7599532 bytes (7.2 MB)
==================================================
downloaded 7.2 MB

trying URL 'https://cloud.r-project.org/src/contrib/Rcpp_1.0.7.tar.gz'
Content type 'application/x-gzip' length 2941808 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

trying URL 'https://cloud.r-project.org/src/contrib/isoband_0.2.5.tar.gz'
Content type 'application/x-gzip' length 1671911 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

Error in eval(exprs[i], envir) : object 'confint.default' not found
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo tidyverse/tidyverse@HEAD
```
```r
> install.packages("tidyverse")
Installing package into ‘/usr/lib/R/library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/tidyverse_1.3.1.tar.gz'
Content type 'application/x-gzip' length 702779 bytes (686 KB)
==================================================
downloaded 686 KB

Error in eval(exprs[i], envir) : object 'confint.default' not found
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo tidyverse/tidyverse@HEAD
stringi (1.6.2 -> 1.7.2) [CRAN]
Rcpp    (NA    -> 1.0.7) [CRAN]
isoband (NA    -> 0.2.5) [CRAN]
Skipping 1 packages ahead of CRAN: data.table
Installing 3 packages: stringi, Rcpp, isoband
Installing packages into ‘/usr/lib/R/library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/stringi_1.7.2.tar.gz'
Content type 'application/x-gzip' length 7599532 bytes (7.2 MB)
==================================================
downloaded 7.2 MB

trying URL 'https://cloud.r-project.org/src/contrib/Rcpp_1.0.7.tar.gz'
Content type 'application/x-gzip' length 2941808 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

trying URL 'https://cloud.r-project.org/src/contrib/isoband_0.2.5.tar.gz'
Content type 'application/x-gzip' length 1671911 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

Error in eval(exprs[i], envir) : object 'confint.default' not found
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo tidyverse/tidyverse@HEAD
...
...
```

**Comment by englianhu** [comment]
wonder its related to the installation and update packages?
source: [What is the difference between "confint" and "confint.default" when calculating confidence intervals for a logit model in R?](https://stackoverflow.com/a/64920929/3806250)

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by englianhu** [comment]
> This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

How to post in RStudio Community since temporariky on hold, even though the most fundamental `install.packages()` doesn't work.
https://community.rstudio.com/t/account-temporarily-on-hold/91839/4

**Comment by batpigandme** [comment]
Hi @englianhu,
I contacted our community manager and asked them to take a look.

**Comment by EconomiCurtis** [comment]
Hi @englianhu,
I'll get you sorted on community.rstudio.com. Will reach out via email and DM on the community site.

**Comment by englianhu** [comment]
> These links workable to me when startup blank page.
> 
> * Continuing the discussion from [GitHub SSH doesn't work](https://community.rstudio.com/t/github-ssh-doesnt-work/124418/2):
> * Continuing the discussion from [Linux penguin RStudio Startup Blank Page](https://community.rstudio.com/t/linux-rstudio-startup-blank-page/124168/2):
> * [Very common RStudio/git problem+solution: "error: unable to read askpass response from 'rpostback-askpass'" STAT545-UBC/Discussion#93 (comment)](https://github.com/STAT545-UBC/Discussion/issues/93#issuecomment-391606351)

source: https://github.com/rstudio/rstudio/issues/9854#issuecomment-995972092

---

As reference when facing below problems:
- GitHub Tokens
- Startup Blank Page
