### ISSUE TITLE
Time to rename the ‘master’ branch of all repos?

### ISSUE THREAD

**Issue by msberends** [tidyverse/tidyverse#268]
As you are probably well aware, GitHub [has been initialising](https://github.com/github/renaming) new repositories with the more inclusive and neutral branch name `main` instead of `master` since October 1, 2020. By doing so, GiHub follows the statements and actions [as stated by Git and the Software Freedom Conservancy in June 2020](https://sfconservancy.org/news/2020/jun/23/gitbranchname/). 

I noticed that RStudio ([github.com/rstudio/rstudio](https://github.com/rstudio/rstudio)) has already renamed their main branch to `main`, and [also clearly states why](https://github.com/rstudio/rstudio/blob/main/README.md).

So, will tidyverse follow? All of it? Please do 🙂

**Comment by jennybc** [comment]
I imagine we will. Providing tooling to enact and detect this branch rename is being tracked in https://github.com/r-lib/usethis/issues/1243. Once that's done, presumably this will be added to the list of updates we make on each package's next maintenance pass.

(And yes we are aware and adapting our tools, e.g. https://github.com/r-lib/usethis/issues/1245, https://github.com/r-lib/usethis/issues/1156)
