### ISSUE TITLE
`tidyverse` loads `%<>%` but not `%T>%`

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/tidyverse#273]
Is `tidyverse` loading `magrittr` or not? When I load `tidyverse`, pipe `%<>%` works, however 
```r
could not find function "%T>%"
```

**Comment by batpigandme** [comment]
No, it does not load magrittr by default. Any pipes that are attached without expressly calling `library(magrittr)` are re-exported by another tidyverse package.
