### ISSUE TITLE
Ggplot 2 labels produced with for loop

### ISSUE THREAD

**Issue by BB1464** [tidyverse/tidyverse#275]
Hi Good Morning All,
     Please I have some visualization in which I generated with for loop, but when I tried to modify the labels it is not showing on the plot. Please how do I resolve this? Find the code below.

for (i in 2:3) {
  print(paste('----',names(iris[i]),'----'))
  print(ggplot(iris,aes(x=Sepal.Length,y=iris[,i]))+geom_point())+xlab('Sepal.Length')+ylab(colnames(iris[i]))
  Sys.sleep(1)
}

Thank you for your anticipated response.

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
