### ISSUE TITLE
Insert value in a new column based on the number of rows

### ISSUE THREAD

**Issue by agronomofiorentini** [tidyverse/tidyverse#277]
Hi and thanks to develop this universe package that i am using everyday.

I have a dataset consisting of 2871 data and I would like to create a column based on a condition.

From the 1st to the 30th row the value Init must be inserted in the column.
from 31 to 210 row the value Mid must be inserted in the column
from 211 to 239 row the column must contain the value End

This must be in a loop that allows the insertion of values up to 2871 always with these classes but starting from the 240 and so on.

You can download the dataset here.

https://drive.google.com/file/d/1Hbdw-UuwM46YpkSIXnz4qTSg1WBJLICd/view?usp=sharing

There is a function or a method in tidyverse to do so?

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
