### ISSUE TITLE
Install tidyverse in R4.1.2, Apple Silicon Mac

### ISSUE THREAD

**Issue by Lorenzopala** [tidyverse/tidyverse#278]
I cannot install tidyverse in R 4.1.2. with the following message：

> install.packages("tidy",dependencies = TRUE)
Warning in install.packages :
  package ‘tidy’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by jennybc** [comment]
I suspect this is just a typo. Try `install.packages("tidyverse")`.

**Comment by Lorenzopala** [comment]
> I suspect this is just a typo. Try `install.packages("tidyverse")`.

Thank you very much! It has been successfully installed.
