### ISSUE TITLE
External dependencies

### ISSUE THREAD

**Issue by ACalleros** [tidyverse/tidyverse#280]
I recently migrated to Manjaro  and I had a lot of troubles installing the tidyverse because I couldn't find the dependencies on the manual or the web page (https://www.tidyverse.org/). I think it would be of great use if you could make the documentation a bit clearer, kind of what they did on the sf package (https://github.com/r-spatial/sf/).

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, no one else has requested it before and it would a hassle to keep up to date, given that the individual packages already declare their needed system requirements. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
