### ISSUE TITLE
Include glue in the tidyverse

### ISSUE THREAD

**Issue by vorpalvorpal** [tidyverse/tidyverse#285]
It's almost impossible to work with strings without glue. Having just looked up 'glue' in the issues here, I discovered str_glue. That's great, but it is not easily discoverable. When beginners google for string formatting they will find 'glue', not 'str_glue'. Surely it would be more convenient to just attach glue rather than have a new wrapper function people have to discover.

**Comment by hadley** [comment]
Glue is already included in the tidyverse, it's just not attached when you `library(tidyverse)`. Attaching additional packages is something that we have to do with great care, and there's limited advantages over just using `str_glue()`, so we're not planning on changing things in the short term.
