### ISSUE TITLE
R Version 3.6.3 vs. 4.0 for tidyverse 

### ISSUE THREAD

**Issue by gourichi** [tidyverse/tidyverse#290]
Tidyverse used to work fine with R version of 3.6.3 till Oct-2021 and now throws an error "ICU init failed: U_FILE_ACCESS_ERROR"

Any idea how to rectify this? so that tidyverse can still work in the same R version of 3.6.3

**Comment by hadley** [comment]
The tidyverse works for R 3.4 and later, as validated by our regular automated tests. It's likely to be configuration problem on your end, but you haven't provided any details.
