### ISSUE TITLE
Extraneous `tidyverse_conflicts()` for re-exported functions

### ISSUE THREAD

**Issue by statisfactions** [tidyverse/tidyverse#291]
`tidyverse::tidyverse_conflicts()` gives what I think is an extraneous conflict between `dplyr::filter()` and  `simpr::filter()`, even though `simpr::filter()` is just a re-export of the generic S3 method of `dplyr::filter()`.

``` r
suppressPackageStartupMessages(library(simpr))
library(tidyverse)
packageVersion("tidyverse")
#> [1] '1.3.1.9000'
tidyverse_conflicts()
#> ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
#> x dplyr::filter() masks simpr::filter(), stats::filter()
#> x dplyr::lag()    masks stats::lag()
```

<sup>Created on 2022-03-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I expected `tidyverse_conflicts()` to only flag the conflict with `stats::filter()`. The `simpr` package has many other re-exports of `dplyr` methods, but for some reason only `filter()` shows up in `tidyverse_conflicts()`.

**Comment by hadley** [comment]
The tidyverse conflict detection mechanism is rather unsophisticated. I'm not sure it's worth trying to improve it, or if we're better off steering people towards https://conflicted.r-lib.org.
