### ISSUE TITLE
Tidyverse does not install because libiconv.so.2 file cannot be found

### ISSUE THREAD

**Issue by arinbasu** [tidyverse/tidyverse#295]
I cannot install tidyverse using `install.packages("tidyverse")` because installation of xml2 and rvest fails as the installation cannot find `libiconv.so.2` file although the file exists. 

How do I fix this?

I am not sure this is a bug but I cannot install tidyverse on a linux machine (linux distro: Void Linux, x86_64)

I cannot install tidyverse as xml2 and rvest could not be installed. 
These two packges could not be installed because the installation could not find libiconv.so.2 file.
My distro does not package `libiconv`, so I cannot load that in any way. 
I also installed jupyterlab using conda environment using mambaforge, and there IS libiconv.so.2 file in

`/home/$(my_username)/mambaforge/lib`
And `/home/$(my_username)/mambaforge` is in the PATH.

How do I correct this error?
I have installed tidyverse in other machines, and never faced this issue.

Any guidance will be greatly appreciated.

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
