### ISSUE TITLE
library(tidyverse) incompatible architecture on M1 Pro?

### ISSUE THREAD

**Issue by jordanjpparker** [tidyverse/tidyverse#300]
OS: macOS Monterey 12.4 
Chipset: M1 Pro

Within RStudio I have installed `tidyverse` fine using `install.packages('tidyverse`), however using `library(tidyverse)` returns the following error:

`Error: package or namespace load failed for ‘tidyverse’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/<user>/Library/R/arm64/4.2/library/colorspace/libs/colorspace.so':
  dlopen(/Users/<user>/Library/R/arm64/4.2/library/colorspace/libs/colorspace.so, 0x0006): tried: '/Users/<user>/Library/R/arm64/4.2/library/colorspace/libs/colorspace.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))`

Uninstalling and reinstalling it does not work. Is it possible it's defaulting to the x86 architecture when installing from CRAN rather than the 64-bit?

**Comment by hadley** [comment]
You probably need to specifically reinstall the colorspace package. It definitely all works on an M1.
