### ISSUE TITLE
dplyr is not loading properly with recent update of tidyverse

### ISSUE THREAD

**Issue by yuvanpradeep** [tidyverse/tidyverse#302]
Issue start date: 2022-07-18

I have installed tidyverse using the below command 
install.packages("tidyverse", lib = "/databricks/spark/R/lib")

And, when I try to use `library(dplyr)` in the next step. I am getting the following error
Note: It was working till 2022-07-17

```
Error : package or namespace load failed for ‘dplyr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
namespace ‘rlang’ 0.4.11 is already loaded, but >= 1.0.2 is required
Some( Error: package or namespace load failed for ‘dplyr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): )
```

System settings: 

R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

**Comment by hadley** [comment]
You need to close all open instances of R/RStudio, re-install rlang (`install.packages("rlang"))` and try again.
