### ISSUE TITLE
`tidyverse_conflicts()` does not list conflicts with `base` functions

### ISSUE THREAD

**Issue by duckmayr** [tidyverse/tidyverse#307]
I am using `tidyverse` version 1.3.1 on R version 4.1.2 with RStudio version 2022.07.1; my operating system is Ubuntu 22.04.1. When I load the `tidyverse` package, it warns me that `dplyr::filter()` masks `stats::filter()` and that `dplyr::lag()` masks `stats::lag()`, but not of the conflicts with the `base` functions `setdiff()`, `setequal()`, `intersect()`, or `union()`.
So when I run

```r
library(tidyverse)
```

I see

![image](https://user-images.githubusercontent.com/20823742/184406432-725ccb79-514c-41b6-8eb9-72c377b318b3.png)

while I would have expected to see something like 

![image](https://user-images.githubusercontent.com/20823742/184406732-09ea2239-a913-4529-8da1-f270b1d61a8d.png)

At first I thought this was simply because `dplyr::intersect()` and the others not listed were S3 generics, but `dplyr::filter` which **is** listed is *also* an S3 generic. Is this intended behavior? If so, what's the rule governing which are listed and which aren't?

**Comment by hadley** [comment]
Those functions are special cases because they've been designed to have the same behaviour as the base functions.
