### ISSUE TITLE
install problem -- Error in library(tidyverse) : there is no package called ‘tidyverse’

### ISSUE THREAD

**Issue by hubbertsmith** [tidyverse/tidyverse#325]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

I install package "tidyverse"
next 
>library(tidyverse)

Error in library(tidyverse) : there is no package called ‘tidyverse’

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

```r
# insert reprex here
Rstudio Version 1.1.456 – © 2009-2018 RStudio, Inc.
R version
platform       x86_64-conda-linux-gnu      
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          2.0                         
year           2022                        
month          04                          
day            22                          
svn rev        82229                       
language       R                           
version.string R version 4.2.0 (2022-04-22)
nickname       Vigorous Calisthenics

**Comment by hadley** [comment]
You need to install it first with `install.packages("tidyverse")`

**Comment by hubbertsmith** [comment]
Thanks Hadley
yes, I did that ... install.packages("tidyverse")  first
I tried it without renv and with renv
same symptoms
when I get to the "library(tidyverse)" line it throws the error above
thanks sincerely, for your help here

**Comment by batpigandme** [comment]
> I tried it again, >>renv<< appears to throw an error related to curl ... should I pursue this in a different place?

Do other packages install and load successfully? If so, then the problem is probably not related to the tidyverse package itself. 🙂

**Comment by hubbertsmith** [comment]
thanks for the help. Yes I am in a conda+anaconda situation. I can try it on a new install, just R. thanks for the pointer
FWIW user feedbabck -- the environments and env "helpers" are a constant problem ... can we get these out of the way until they are actually needed?

**Comment by batpigandme** [comment]
> the environments and env "helpers" are a constant problem ... can we get these out of the way until they are actually needed

There's no need to work in a managed environment…unless you need to work in one. That's definitely outside the scope of the tidyverse package though!

**Comment by hubbertsmith** [comment]
good advice, thanks
***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by hubbertsmith** [comment]
root cause appears to be tidyverse install
Ubuntu 22.10 clean install 
apt update
apt upgrade -y
apt install wget curl gdebi openssh-server
apt install r-base
apt install rstudio-2022.12.0-353-amd64.deb
rstudio -- opens and runs just fine

install.packages("tidyverse") fails with a "no package libcurl found"
---------------------
install.packages("tidyverse")
Installing package into ‘/home/hubbert/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
also installing the dependencies ‘gargle’, ‘curl’, ‘systemfonts’, ‘textshaping’, ‘googledrive’, ‘googlesheets4’, ‘httr’, ‘ragg’, ‘rvest’, ‘xml2’

trying URL 'https://cloud.r-project.org/src/contrib/gargle_1.3.0.tar.gz'
Content type 'application/x-gzip' length 345590 bytes (337 KB)
==================================================
downloaded 337 KB

trying URL 'https://cloud.r-project.org/src/contrib/curl_5.0.0.tar.gz'
Content type 'application/x-gzip' length 682047 bytes (666 KB)
==================================================
downloaded 666 KB

trying URL 'https://cloud.r-project.org/src/contrib/systemfonts_1.0.4.tar.gz'
Content type 'application/x-gzip' length 81757 bytes (79 KB)
==================================================
downloaded 79 KB

trying URL 'https://cloud.r-project.org/src/contrib/textshaping_0.3.6.tar.gz'
Content type 'application/x-gzip' length 35722 bytes (34 KB)
==================================================
downloaded 34 KB

trying URL 'https://cloud.r-project.org/src/contrib/googledrive_2.0.0.tar.gz'
Content type 'application/x-gzip' length 1593656 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

trying URL 'https://cloud.r-project.org/src/contrib/googlesheets4_1.0.1.tar.gz'
Content type 'application/x-gzip' length 223314 bytes (218 KB)
==================================================
downloaded 218 KB

trying URL 'https://cloud.r-project.org/src/contrib/httr_1.4.5.tar.gz'
Content type 'application/x-gzip' length 160874 bytes (157 KB)
==================================================
downloaded 157 KB

trying URL 'https://cloud.r-project.org/src/contrib/ragg_1.2.5.tar.gz'
Content type 'application/x-gzip' length 427859 bytes (417 KB)
==================================================
downloaded 417 KB

trying URL 'https://cloud.r-project.org/src/contrib/rvest_1.0.3.tar.gz'
Content type 'application/x-gzip' length 94659 bytes (92 KB)
==================================================
downloaded 92 KB

trying URL 'https://cloud.r-project.org/src/contrib/xml2_1.3.3.tar.gz'
Content type 'application/x-gzip' length 283965 bytes (277 KB)
==================================================
downloaded 277 KB

trying URL 'https://cloud.r-project.org/src/contrib/tidyverse_2.0.0.tar.gz'
Content type 'application/x-gzip' length 704618 bytes (688 KB)
==================================================
downloaded 688 KB

* installing *source* package ‘curl’ ...
** package ‘curl’ successfully unpacked and MD5 sums checked
** using staged installation
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl
--------------------------- [ANTICONF] --------------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: curl/curl.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘curl’
* removing ‘/home/hubbert/R/x86_64-pc-linux-gnu-library/4.2/curl’
Warning in install.packages :
  installation of package ‘curl’ had non-zero exit status
* installing *source* package ‘systemfonts’ ...
** package ‘systemfonts’ successfully unpacked and MD5 sums checked
** using staged installation
Package fontconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `fontconfig.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fontconfig' found
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'freetype2' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lfontconfig -lfreetype
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find the fontconfig freetype2 library. Try installing:
 * deb: libfontconfig1-dev (Debian, Ubuntu, etc)
 * rpm: fontconfig-devel (Fedora, EPEL)
 * csw: fontconfig_dev (Solaris)
 * brew: freetype (OSX)
If fontconfig freetype2 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a fontconfig freetype2.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: fontconfig/fontconfig.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘systemfonts’
* removing ‘/home/hubbert/R/x86_64-pc-linux-gnu-library/4.2/systemfonts’
Warning in install.packages :
  installation of package ‘systemfonts’ had non-zero exit status
* installing *source* package ‘xml2’ ...
** package ‘xml2’ successfully unpacked and MD5 sums checked
** using staged installation
Package libxml-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libxml-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libxml-2.0' found
Package libxml-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libxml-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libxml-2.0' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lxml2
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libxml-2.0 was not found. Try installing:
 * deb: libxml2-dev (Debian, Ubuntu, etc)
 * rpm: libxml2-devel (Fedora, CentOS, RHEL)
 * csw: libxml2_dev (Solaris)
If libxml-2.0 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libxml-2.0.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘xml2’
* removing ‘/home/hubbert/R/x86_64-pc-linux-gnu-library/4.2/xml2’
Warning in install.packages :
  installation of package ‘xml2’ had non-zero exit status
ERROR: dependency ‘systemfonts’ is not available for package ‘textshaping’
* removing ‘/home/hubbert/R/x86_64-pc-linux-gnu-library/4.2/textshaping’
Warning in install.packages :
  installation of package ‘textshaping’ had non-zero exit status
ERROR: dependency ‘curl’ is not available for package ‘httr’
* removing ‘/home/hubbert/R/x86_64-pc-linux-gnu-library/4.2/httr’
Warning in install.packages :
  installation of package ‘httr’ had non-zero exit status
ERROR: dependency ‘httr’ is not available for package ‘gargle’
* removing ‘/home/hubbert/R/x86_64-pc-linux-gnu-library/4.2/gargle’
Warning in install.packages :
  installation of package ‘gargle’ had non-zero exit status
ERROR: dependencies ‘systemfonts’, ‘textshaping’ are not available for package ‘ragg’
* removing ‘/home/hubbert/R/x86_64-pc-linux-gnu-library/4.2/ragg’
Warning in install.packages :
  installation of package ‘ragg’ had non-zero exit status
ERROR: dependencies ‘httr’, ‘xml2’ are not available for package ‘rvest’
* removing ‘/home/hubbert/R/x86_64-pc-linux-gnu-library/4.2/rvest’
Warning in install.packages :
  installation of package ‘rvest’ had non-zero exit status
ERROR: dependencies ‘gargle’, ‘httr’ are not available for package ‘googledrive’
* removing ‘/home/hubbert/R/x86_64-pc-linux-gnu-library/4.2/googledrive’
Warning in install.packages :
  installation of package ‘googledrive’ had non-zero exit status
ERROR: dependencies ‘curl’, ‘gargle’, ‘googledrive’, ‘httr’ are not available for package ‘googlesheets4’
* removing ‘/home/hubbert/R/x86_64-pc-linux-gnu-library/4.2/googlesheets4’
Warning in install.packages :
  installation of package ‘googlesheets4’ had non-zero exit status
ERROR: dependencies ‘googledrive’, ‘googlesheets4’, ‘httr’, ‘ragg’, ‘rvest’, ‘xml2’ are not available for package ‘tidyverse’
* removing ‘/home/hubbert/R/x86_64-pc-linux-gnu-library/4.2/tidyverse’
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp6po1Qk/downloaded_packages’

**Comment by batpigandme** [comment]
If you look at the error messages for the packages that didn't install succesfully, I think they all have the same sort of "call to action" re needing a system requirement in the `PKG_CONFIG_PATH`, e.g.

```
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing libcurl.pc' to the PKG_CONFIG_PATH environment variable No package 'libcurl' found Package libcurl was not found in the pkg-config search path. Perhaps you should add the directory containing libcurl.pc'
to the PKG_CONFIG_PATH environment variable
```

**Comment by hadley** [comment]
I think pak might automatically report what system dependencies you need, or you might try installing binaries from https://packagemanager.posit.co/client/#/.

**Comment by hubbertsmith** [comment]
thanks for your help
I finally got it sorted
my /etc/environment file:
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/xml:/usrshare/doc:/usr/share:/usr/lib/x86_64-linux-gnu:/usr/include/fontconfig"
plus followed the error messages and installed missing libraries (like 8 of
them)

(for the record, this was an Rstudio install thing, not a tidyverse thing)
did I do something wrong? I've installed Rstudio many times, and never had
to fight it like this?

Mara and Hadley, thanks again for your help, I deeply appreciate it

***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by batpigandme** [comment]
> did I do something wrong? I've installed Rstudio many times, and never had to fight it like this?

It doesn't sound like you did anything wrong (though, as you ended up seeing, I think you made life easier once you worked outside of Conda). There are two-ish sort of categories of things you faced, which are pretty typical of R setup: having the paths right so your computer knows where to look for stuff, and having the necessary _non_-R pacakges (e.g. libcurl4-openssl-dev, libssl-dev, libxml2-dev) you need for the R packages you're installing to work.

We've tried to make the latter bit easier with [pak](https://pak.r-lib.org/index.html), which, as Hadley pointed out, automatically reports system dependencies.

Sorry I can't be of more help.

**Comment by hubbertsmith** [comment]
You were of great help! without your guidance I would still be fighting
that problem.
sincerely, thank you
I will take a serious go at pak,
hope I can return the favor!


***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by yachenhu** [comment]
I tracked the log for missing libs in this `ANTICONF` block.
```
--------------------------- [ANTICONF] --------------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
```
Then install those libs.
```
sudo apt-get install libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libcurl4-openssl-dev
```
After that, install tidyverse, and it worked.
```
sudo /usr/bin/Rscript -e 'install.packages("tidyverse")'
```

**Comment by zenkavi** [comment]
For Mac users (on R 4.4.1) the following might help: 
```
brew install harfbuzz fribidi libtiff
```
Before this I had also installed the following for other purposes
```
brew install openssl readline sqlite3 xz zlib tcl-tk
```
