### ISSUE TITLE
R changed its usual behavior causing entire code base to collapse

### ISSUE THREAD

**Issue by Yann-C-INN** [tidyverse/tidyverse#330]
https://community.rstudio.com/t/warning-converted-to-error-entire-code-base-damaged/169787

Hi guys. I also opened a topic in posit community.
basically, what used to be a warning is now an error and it makes my entire code to collapse.

specificaly, mutate function can no longer accept numeric values to turn into NA

```
Error: (converted from warning) There were 2 warnings in `mutate()`.
The first warning was:
ℹ In argument: `across(contains("COUNTER"), as.numeric)`.
Caused by warning:
! NAs introduced by coercion
ℹ Run dplyr::last_dplyr_warnings() to see the 1 remaining warning.
```

Thank you. I did not update R recently, it worked fine yesterday

`option(warn =1) did the trick and thanks Posit community`

**Comment by hadley** [comment]
This must have been something you did, because we don't touch the value of the `warn` option.
