### ISSUE TITLE
tidyverse installation fail on MacOS 10.11.6 el capitan

### ISSUE THREAD

**Issue by gli81** [tidyverse/tidyverse#331]
Hello,

I am currently in the process of installing the tidyverse package on my MacOS 10.11.6 system. I have R version 3.6.3 and R Studio version 1.1.463, which are both the latest versions compatible with my operating system.

Despite my efforts, I have encountered persistent failures in attempting to install tidyverse. Upon analyzing the error messages, it appears that the issue is related to the age of my operating system. Specifically, a crucial dependency known as "systemfonts" necessitates a .o file from MacOS 10.13, a version newer than my current 10.11.

This incompatibility has resulted in error messages similar to the one provided below:

```r
ld: warning: object file (/private/var/folders/fr/myfcbqmj1lz2lbklhxkr1s5c0000gn/T/RtmpqdxJab/R.INSTALL472a67fa289e/systemfonts/.deps/lib/libpng.a(pngwio.o)) was built for newer OSX version (10.13) than being linked (10.11)
```

Your willingness to assist is greatly appreciated. Your guidance could encompass methods for bypassing the dependency, procuring a pre-compiled tidyverse package for binary installation, or acquiring the necessary .o files that are currently absent on my system. Your support is invaluable. Thank you!

**Comment by artmg** [comment]
@gli81 The inference from jennybc's post is that you are seeing a warning, but it is possible that the tidyverse package is still being installed successfully. Have you tried

```
tidyverse::tidyverse_sitrep()
```

If this fails then, yes, you are hitting an error during the installation...

But if it works, it may give you an idea of which parts of the tidyverse are available to you, and which parts you might have to source in a different way. The tidyverse is a 'metapackage' that pulls together a whole set of individual packages, and you may be able to achieve your objectives by installing individual packages. And for those that fail, if you really need them for your objectives, perhaps you can choose versions of the package that are known to work with your OS version.

**Comment by gli81** [comment]
Dear @jennybc,

I wanted to express my gratitude for your prompt response. I apologize for not getting back to you sooner. I followed your advice and attempted to look for error messages when installing tidyverse. I encountered an error message that appears to be related to the systemfonts package, which is affecting the installation of tidyverse.

Here is the error message I received:

```
Error: package or namespace load failed for ‘systemfonts’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-systemfonts/00new/systemfonts/libs/systemfonts.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-systemfonts/00new/systemfonts/libs/systemfonts.so, 6): Symbol not found: _inflateValidate
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-systemfonts/00new/systemfonts/libs/systemfonts.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-systemfonts/00new/systemfonts/libs/systemfonts.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts’
Warning in install.packages :
  installation of package ‘systemfonts’ had non-zero exit status
```

**Comment by gli81** [comment]
Dear @artmg,

Thank you for your response. I appreciate your assistance in troubleshooting this issue. I followed your suggestion and attempted to use the tidyverse::tidyverse_sitrep() function. Unfortunately, I received an error message stating that there is no package called tidyverse, which suggests that the initial installation was not successful.

In an effort to resolve the issue, I proceeded to reinstall the tidyverse package. However, during this attempt, I encountered the following error message:

```
Error: package or namespace load failed for ‘systemfonts’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-systemfonts/00new/systemfonts/libs/systemfonts.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-systemfonts/00new/systemfonts/libs/systemfonts.so, 6): Symbol not found: _inflateValidate
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-systemfonts/00new/systemfonts/libs/systemfonts.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-systemfonts/00new/systemfonts/libs/systemfonts.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts’
Warning in install.packages :
  installation of package ‘systemfonts’ had non-zero exit status
```

It appears that the issue may indeed be related to the systemfonts package, which is a dependency for the tidyverse package.

Your insights and suggestions are greatly appreciated. If you have any further recommendations or if there's anything else I should try, please let me know.

Thank you once again for your assistance.

**Comment by hadley** [comment]
@gli81 sorry we can't help more; our general philosophy is to support the tidyverse on software up to 5 years old, and it looks like el capitan was released 8 years ago.
