### ISSUE TITLE
tidyverse ingest conventions

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidyverse#34]
*The requested brain dump to get this started.*

- Function that reads a `thingy` should be named `read_thingy()`. The opposite, when it exists, should be named `write_thingy()`.
- If it makes sense, return a tibble.
  - Any package that creates tibbles should import tibble, to reduce gotchas around, e.g., the `drop = FALSE` behaviour of `[` or the lack of partial matching on `$`.
  - If `thingy` has no data, return a tibble with 0 rows and 0 columns.
- Don't have row names.
- `col_names` is the tidyverse answer to `header = TRUE`. Either logical indicating that first row gives variable names or character vector of names.
- Don't mess with column names, i.e. don't modify non-syntactic names. Exceptions:
  - Fill in missing column names.
  - De-duplicate column names.
- Don't coerce character to factor, `stringsAsFactors = FALSE`.
- Do guess column types *under what circumstances? according to what rules?*
  - Provide control over how much data to use for the guessing, `guess_max = min(1000, n_max)`*
  - Recognize dates and date-times, for some universe of default formats. *And always convert to POSIXct?*
- `col_types` is the tidyverse answer to `colClasses`. There is an entire system for type specification, with short codes or more general "collectors".
  - *consider readr's "problems" and printed/returned colspec*
- *something about locale*
- *something about UTF-8 encoding*
- Explicit control over rows to skip, unrelated to the data: `skip = 0, n_max = Inf`.
- Control over rows (or parts thereof) to skip, based on the data
  - `comment`
  - a vector of `NA` values. Use `quoted_na` to specify what happens to `"NA"`.
- *Something about empty rows/columns. Proposal: include and fill with NA when leading (and not explicitly skipped) or embedded. Treatment of trailing empty rows/columns will depend on context (e.g. possible to include with readr, impossible with readxl).*
- *something about reading from file, compressed file, URL, connection, memory*
- *something about chunked reading*
- whitespace trimming?
- progress?
- Recommendations for implementation? Or a package?

**Comment by hadley** [comment]
* It needs to both import tibble and import a function from tibble (otherwise doesn't actually trigger the import)

* Something about locale includes: functions should be designed to return identical results when called on different systems. This means not taking deriving default values from the OS.

**Comment by jennybc** [comment]
> It needs to both import tibble and import a function from tibble (otherwise doesn't actually trigger the import).

Maybe tibble should have a function expressly for this purpose? And it could somehow also be used to summon "what is a tibble? go here for a list of need-to-know facts about how it differs from data.frame".

**Comment by jennybc** [comment]
Recommendation for standard flavour of `NA` used for missing data?

In base R, it's logical.

In readr, it's character.

In readxl, it's currently numeric.

**Comment by hadley** [comment]
I feel like logical is probably the most reasonable.
