### ISSUE TITLE
Big Endian stops feather, which stops tidyverse

### ISSUE THREAD

**Issue by shapenaji** [tidyverse/tidyverse#36]
Can't install tidyverse on the server due to Big Endian-ness:

Is there a way to install tidyverse without the feather dependency?

```
* installing *source* package ‘feather’ ...
** package ‘feather’ successfully unpacked and MD5 sums checked
Platform is big endian. This is currently unsupported.
ERROR: configuration failed for package ‘feather’
* removing **********/packrat/lib/x86_64-pc-linux-gnu/3.3.2/feather’
ERROR: dependency ‘feather’ is not available for package ‘tidyverse’
* removing ‘**********/packrat/lib/x86_64-pc-linux-gnu/3.3.2/tidyverse’

The downloaded source packages are in
	‘/tmp/Rtmpi2llVt/downloaded_packages’
```

**Comment by hadley** [comment]
Hmmm, because of this pain, it might be better to make feather a suggested package.

**Comment by kathy0305** [comment]
Same problem here, I know that I can install all the other packages individually, but it defeats the purpose of tidyverse.

**Comment by kathy0305** [comment]
I just tried to install it again, this time a problem with scales
But in this case I was able to install "scales" first and then install tidyverse, no problems! 

install.packages("scales")
