### ISSUE TITLE
Latest tidyverse build doesn't load

### ISSUE THREAD

**Issue by rossbennett** [tidyverse/tidyverse#38]
Hello, all!

Forgive me if this is my failing; I'm mighty new to R and the tidyverse.

The latest packages on CRAN mirrors seems to be corrupted.  Here's what we get in both R and RStudio on both machines we've installed to.

>install.packages("tidyverse")
trying URL 'https://cran.revolutionanalytics.com/bin/macosx/mavericks/contrib/3.3/tidyverse_1.1.1.tgz'
Content type 'application/octet-stream' length 37228 bytes (36 KB)
==================================================
downloaded 36 KB

The downloaded binary packages are in
	/var/folders/4s/646fsd2d5zzdylghrvwwj76m0000gn/T//Rtmp1LD6W9/downloaded_packages
> library(tidyverse)
Error : object ‘as_factor’ is not exported by 'namespace:forcats'
Error: package or namespace load failed for ‘tidyverse’
> 

I've sort of worked around it by manually retrieving the earlier release and installing 1.0.0 using the package installers, though I'm not entirely confident that fixes everything. I do get the expected loading messages.

Thanks!

**Comment by hadley** [comment]
You'll need to update forcats. I forgot that I only just added that function 😦

**Comment by sjackman** [comment]
I've just experience this bug as well. It's resolved easily by installing `forcats`. I'm not terribly familiar with the R dependency mechanisms. Should `tidyverse` depend on a minimum version of `forcats`?

**Comment by hadley** [comment]
Yes, it should :(  Or I should have imported a function that's been in forcats for longer
