### ISSUE TITLE
when using tidyverse_update()... Warning: packages ‘ggplot2’, ‘tidyr’ are in use and will not be installed

### ISSUE THREAD

**Issue by ahcyip** [tidyverse/tidyverse#41]
I have to load tidyverse
`library(tidyverse)`
so that I can run 
`tidyverse_update()`
but then I get the result:
Warning: packages ‘ggplot2’, ‘tidyr’ are in use and will not be installed
Am I doing something wrong?

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

**Comment by ahcyip** [comment]
``` r
tidyverse_update()
#> Error in eval(expr, envir, enclos): could not find function "tidyverse_update"
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats
tidyverse_update()
#> The following packages are out of date:
#>  * ggplot2 (2.2.0 -> 2.2.1)
#>  * tidyr   (0.6.0 -> 0.6.1)
#> Update now?

#1: Yes
#2: No

# Selection: Yes
# Warning: packages ‘ggplot2’, ‘tidyr’ are in use and will not be installed

**Comment by hadley** [comment]
Hmmm, I'm not sure what system you're on that's preventing this, but try not loading tidyverse and instead just running `tidyverse::tidyverse_update()`

**Comment by ahcyip** [comment]
Thank you! `tidyverse::tidyverse_update()` worked.

Rstudio 1.0.136 on Windows 10
`tidyverse_update()
#Error: could not find function "tidyverse_update"`

**Comment by ahcyip** [comment]
> tidyverse::tidyverse_update()
The following packages are out of date:
 * purrr  (0.2.2 -> 0.2.2.2)
 * readr  (1.0.0 -> 1.1.0)
 * tibble (1.2 -> 1.3.0)
 * tidyr  (0.6.1 -> 0.6.2)
Update now?

1: Yes
2: No

Selection: 1
package ‘purrr’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘purrr’
package ‘readr’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘readr’
package ‘tibble’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘tibble’
package ‘tidyr’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘tidyr’
> library(tidyverse) # 6 core tidyverse packages
Loading tidyverse: ggplot2
Loading tidyverse: tibble
Loading tidyverse: tidyr
Loading tidyverse: readr
Loading tidyverse: purrr
Loading tidyverse: dplyr
Error : .onAttach failed in attachNamespace() for 'tidyverse', details:
  call: FUN(X[[i]], ...)
  error: there is no package called ‘tibble’
Error: package or namespace load failed for ‘tidyverse’

**Comment by JohnRoelofse** [comment]
I ran into the same problem now. I just restarted R Studio and used `install.packages()` to update each package that couldn't update using `tidyverse_update()`.
