### ISSUE TITLE
package or namespace load failed for ‘tidyverse’

### ISSUE THREAD

**Issue by DongdongMa** [tidyverse/tidyverse#42]
> library(tidyverse)
Error : object ‘as_factor’ is not exported by 'namespace:forcats'
Error: package or namespace load failed for ‘tidyverse’

**Comment by hadley** [comment]
You'll need to upgrade forcats

**Comment by DongdongMa** [comment]
Thank you.

**Comment by sjackman** [comment]
Duplicate of #38
