### ISSUE TITLE
SDMX

### ISSUE THREAD

**Issue by Monduiz** [tidyverse/tidyverse#43]
Given how amazing tidyverse is and how xml2 is so much better, how hard would it be to include teh capability of processing SDMX-ML within tidyverse? Statistics Canada is using the Statistical Data and Metadata Exchange (SDMX) framework to release multidimensional data and I am looking for a simpler way to process that data. 

There is the package RSDMX but I really love the logic and syntax throughout tidyverse.

Would this be possible?

**Comment by hadley** [comment]
Unfortunately it's unlikely to be something I have the time for, but you might be able to find other people in the community interested in working on it. I'd start with ROpenSci.

**Comment by Monduiz** [comment]
Thanks, Hadley, I will look ROpenSci up.
