### ISSUE TITLE
Error while loading 'tidyverse' package for R version 3.3.3

### ISSUE THREAD

**Issue by shatadrusaha** [tidyverse/tidyverse#53]
I am getting an error when I try to load 'tidyverse' library in R Studio. I installed the package without any error.
This is the log, when I installed the package:

> > install.packages("tidyverse")
> Installing package into ‘C:/Users/Shadz/Documents/R/win-library/3.3’
> (as ‘lib’ is unspecified)
> also installing the dependency ‘jsonlite’
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/jsonlite_1.3.zip'
> Content type 'application/zip' length 1122936 bytes (1.1 MB)
> downloaded 1.1 MB
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/tidyverse_1.1.1.zip'
> Content type 'application/zip' length 41948 bytes (40 KB)
> downloaded 40 KB

But when I try to load the library, I get the following error.

> > library(tidyverse)
> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
>   there is no package called ‘stringi’
> Error: package or namespace load failed for ‘tidyverse’

Thanks & Regards,
Shatadru Saha

**Comment by hadley** [comment]
I'm not sure how you got into this state, but `install.packages("stringi")` should fix it.

**Comment by shatadrusaha** [comment]
Thanks. That resolved the issue for me. Cheers.
