### ISSUE TITLE
Tidyverse installation error

### ISSUE THREAD

**Issue by jar1karp** [tidyverse/tidyverse#57]
On installing the package (using ref f27f74c) as

```
devtools::install_github('hadley/tidyverse')
```

I get the following:

```
Error : .onAttach failed in attachNamespace() for 'tidyverse', details:
  call: rlang::as_function(.f, ...)
  error: unused argument (collapse = ", ")
Error: loading failed
Execution halted
```

Not sure if this is due to rlang though (have installed that using ref 0756eaf).

**Comment by hadley** [comment]
I've seen this too, but I can't recreate with dev version of rlang, purrr etc.

**Comment by jar1karp** [comment]
I just tried installing again, it seems that `purrr` was also updated from github  and now it works. Likely the most recent commits fixed whatever was causing the error.
