### ISSUE TITLE
mnormt error preventing tidyverse from loading

### ISSUE THREAD

**Issue by nate-d-olson** [tidyverse/tidyverse#65]
I had the following error message when trying to load the `tidyverse` package, 
```
Error: package or namespace load failed for ‘tidyverse’:
 .onLoad failed in loadNamespace() for 'mnormt', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/usr/local/lib/R/3.4/site-library/mnormt/libs/mnormt.so':
  dlopen(/usr/local/lib/R/3.4/site-library/mnormt/libs/mnormt.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib
  Referenced from: /usr/local/lib/R/3.4/site-library/mnormt/libs/mnormt.so
  Reason: image not found
```

I was able to fix the error by installing `mnormt`. I have been using `tidyverse` for awhile now and have not had this issue before. `mnormt` is not listed as a `tidyverse` dependency, I am not sure if this error is specific to my system/ setup or a `tidyverse` bug.

**Comment by jongbinjung** [comment]
Might be that you updated your system to something that replaced `gcc6` with something else, but R was using a `mnormt` package that was compiled with a dynamic link to the old `libgfortran` from `gcc6`? 
That seems to be what the error message is saying, and that would also explain how manually installing `mnormt` resolved the issue (i.e., you recompiled the package, linking it to whatever `libgfortran` is available in your current system)

**Comment by hadley** [comment]
Installing tidyverse seems to bring out a lot of weird package installation bugs. We're working on tools to better diagnose and fix them.

**Comment by lamatko** [comment]
Installing `gcc-gfortran`  package (on CentOS) helped me for installing `mnormt`. For the whole tidyverse I had to install also  `libxml2-devel` for `xml2` package.
