### ISSUE TITLE
tidyverse interfering with ggplot2? cannot access map_data

### ISSUE THREAD

**Issue by RafaRafa** [tidyverse/tidyverse#66]
copied over from stackoverflow: 

https://stackoverflow.com/questions/44205731/tidyverse-interfering-with-ggplot2-cannot-access-map-data?noredirect=1#comment75428898_44205731
This is the output on console of loading ```tidyverse``` then trying to load ```map_data``` with ```ggplot2```
```
> cty0 = ggplot2::map_data("county")
> library(tidyverse)
Loading tidyverse: ggplot2
Loading tidyverse: tibble
Loading tidyverse: tidyr
Loading tidyverse: readr
Loading tidyverse: purrr
Loading tidyverse: dplyr
Conflicts with tidy packages -----------------------------------------------------------------------------------------------
filter(): dplyr, stats
lag():    dplyr, stats
map():    purrr, maps
> cty0 = ggplot2::map_data("county")
Error: ggplot2 doesn't know how to deal with data of class list
```

**Comment by ben-williams** [comment]
Having the same issue:

    states <- map_data("state")  
    Error: ggplot2 doesn't know how to deal with data of class list

**Comment by prdx** [comment]
Any news on this? It somehow works in my RStudio but not in my R console.

**Comment by hadley** [comment]
Minimal reprex:

```R
library(ggplot2)
cty0 <- map_data("county")

library(purrr)
cty0 <- map_data("county")
```

**Comment by tvedebrink** [comment]
I had a similar problem - running identical code in shiny and an embedded rmarkdown document caused an error in rmarkdown but not in the app. The solution I found to work was to replace
`world_map <- map_data("world")`
with
`world_map <- maps::map("world", ".", exact = FALSE, plot = FALSE, fill = TRUE) %>% fortify()`
and then call `ggplot(world_map)` in the code.

**Comment by felipedallalana** [comment]
I have the same problem, my code worked before, now work only in the R console.
The solution provides by @tvedebrink works, however, it is difficult to do subsets.
