### ISSUE TITLE
Error loading R package 'tidyverse' into library

### ISSUE THREAD

**Issue by bilalshakir91** [tidyverse/tidyverse#72]
I get the following error whenever I attempt to load the R package 'tidyverse' onto library:

> library("tidyverse", lib.loc="/Library/Frameworks/R.framework/Versions/3.3/Resources/library")
Error : object ‘as_factor’ is not exported by 'namespace:forcats'
Error: package or namespace load failed for ‘tidyverse’

**Comment by hadley** [comment]
You need to update forcats.
