### ISSUE TITLE
join on logicals

### ISSUE THREAD

**Issue by jahilliard** [tidyverse/tidyverse#73]
I am not sure where to put this, because it is more a feature request and not an issue. But I would really love to be able to join on Logicals.

`inner_join(x = df.1, y = df.2, by = col.1 < col.2)` 

This is very similar to SQL like joining syntax.

**Comment by szaydel** [comment]
@jahilliard: This seems like it would be along the lines of `JOIN ON A = B` in SQL, in which case only rows that fulfill the join condition are `SELECT`ed, remaining are filtered out. I think it is a good idea and I would find it quite useful as well.

**Comment by jahilliard** [comment]
@szaydel : Also, fun fact in most SQL dialects you can actually

`select * from table.1 as one inner join table.2 as two on one.col < two.col`

**Comment by szaydel** [comment]
I always love to hear "most SQL dialects". One problem with SQL, is there are many SQLs. Good tip though to be sure. Hopefully the good folks here will give it a thorough consideration.

**Comment by hadley** [comment]
We're calling this generic joins, and the existing FR is at #2240
