### ISSUE TITLE
Data bases in Tidyverse 

### ISSUE THREAD

**Issue by NastashaVelasco** [tidyverse/tidyverse#75]
Hi guys!!
I am just beginning with R and I am supposed to use the data bases within Tidyverse, how can I access this? because for what I understood Tidyverse was for this imports : broom , dplyr , forcats , ggplot2 , haven , hms , httr , jsonlite , lubridate , magrittr , modelr , purrr , readr , readxl , rvest , stringr , tibble , tidyr , xml2. Some friends told me that some databases like diamonds is available, how can I how get this?
Sorry for this stupid question! In need of help!

**Comment by dchiu911** [comment]
`ggplot2::diamonds`

**Comment by hadley** [comment]
Generally a better place for questions like this is http://community.rstudio.com/
