### ISSUE TITLE
r-lib/boxes has been renamed to r-lib/cli

### ISSUE THREAD

**Issue by serhatcevikel** [tidyverse/tidyverse#76]
r-lib/boxes, a github package and a dependency for tidyverse has been renamed to r-lib/cli. And tidyverse installation is not successful now. 

So the references to the package should be updated.

**Comment by joelgombin** [comment]
+1

**Comment by serhatcevikel** [comment]
I've made a pull request for resolving that issue.

**Comment by IdoBar** [comment]
+1
Waiting for an update
