### ISSUE TITLE
Error in installing tidyverse 1.2.0 to directory with non-english characters

### ISSUE THREAD

**Issue by RobertSkeril** [tidyverse/tidyverse#81]
Hi,
I have Czech special characters in my name and also in name directory in Users folder (Win10). Till now there was no problem with all packages, but now I cannot install tidyverse, because in one command, it cannot read correctly that Czech character "ř" and it uses "x". But when it continues with removing, the right character is used.
Can you please fix it?
Thank you very much.
Robert

```
`* installing *source* package 'tidyverse' ...
** package 'tidyverse' successfully unpacked and MD5 sums checked
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/Mgr. Robert Skexil/Documents/R/win-library/3.4/tidyverse/DESCRIPTION': No such file or directory
Error in file(file, if (append) "a" else "w") : 
  cannot open the connection
ERROR: installing package DESCRIPTION failed for package 'tidyverse'
* removing 'C:/Users/Mgr. Robert Skeřil/Documents/R/win-library/3.4/tidyverse'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\Mgr. Robert Skeřil\Documents\R\win-library\3.4" C:\Users\MGR~1.ROB\AppData\Local\Temp\RtmpQxUs0J/downloaded_packages/tidyverse_1.2.0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status`
```

**Comment by hadley** [comment]
Unfortunately this is a bug in `install.packages()` which we don't have any control over. 

But we're working on an alternative way to install packages, and we can make sure this isn't a problem there.  cc @jimhester

**Comment by RobertSkeril** [comment]
TY for answer. I installed R for a while on kids computer, install tidyverse and then copy the tidyverse folder through network to my computer ... and it work. Not that elegant, but I can work.
Once again thank you!
Robert
