### ISSUE TITLE
Startup message too long for knitr output

### ISSUE THREAD

**Issue by andrewheiss** [tidyverse/tidyverse#92]
The fancy tidyverse 1.2 startup message does not fit in the output of a knitted PDF, and the message width does not respect either the formatR options or R's session width.

MWE:

    ---
    title: "Testing"
    output: 
      pdf_document: 
        latex_engine: xelatex
    ---

    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60),  # For code
                          width = 60)  # For output
    ```

    ```{r}
    library(tidyverse)
    ```

Output: 

![image](https://user-images.githubusercontent.com/73663/32851897-976271e8-c9f3-11e7-9144-a80929088c6c.png)

**Comment by andrewheiss** [comment]
Perhaps something like `options(tidyverse.width = 80)` could be implemented someday?

**Comment by hadley** [comment]
I think your syntax is a little off. You need:

```R
knitr::opts_chunk$set(width = 60)
```

**Comment by andrewheiss** [comment]
Ah, fixed that, thanks! The problem still stands though.

![image](https://user-images.githubusercontent.com/73663/32853710-5fdd8608-c9f9-11e7-8de3-7c23f7799517.png)

**Comment by hadley** [comment]
Seems to be a problem in the package we're using for the output: https://github.com/r-lib/cli/issues/33

**Comment by andrewheiss** [comment]
For now, just setting `options(cli.width = 60)` works:

    ---
    title: "Testing"
    output:
      pdf_document:
        latex_engine: xelatex
    ---

    ```{r setup}
    knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60),  # For code
                          width = 60)  # For output

    options(cli.width = 60)  # For tidyverse loading messages
    ```

    ```{r}
    library(tidyverse)
    ```

![image](https://user-images.githubusercontent.com/73663/32912298-985bb912-cadc-11e7-8263-3c2ba042ae3f.png)

**Comment by jananiravi** [comment]
I still have trouble with the wrapping @andrewheiss I use the suggested `knitr` chunk above. Any suggestions?
![image](https://user-images.githubusercontent.com/8397074/47759394-c9405e00-dc85-11e8-9422-bd093286bdfc.png)

**Comment by andrewheiss** [comment]
If that monospaced section is standard Markdown, knitr won't do any wrapping. That's a Markdown issue, and [it's not solvable yet](https://stackoverflow.com/questions/41238148/how-to-line-wrap-long-lines-inside-markdown-code-blocks-in-githubgitlab) without manually breaking lines to fit on the page.

````
---
title: "Testing"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60),  # For code
                      width = 60)  # For output

options(cli.width = 60)  # For tidyverse loading messages
```

```{r}
library(tidyverse)
```

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

```
Adding some longer text here
* First item
* Second longer item that's not actually full length
* Really long item that should go off the page eventually if I keep typing stuff here and maybe it's there now I'm not sure yet so I'll keep typing
```
````

<img width="543" alt="image" src="https://user-images.githubusercontent.com/73663/48757317-8dcbfa80-ec59-11e8-8a8d-413ff4d1240b.png">
