### ISSUE TITLE
Tidyverse 1.2.1 issue while knitting PDF in Mac

### ISSUE THREAD

**Issue by toouggy** [tidyverse/tidyverse#95]
Hi I can knit PDF files in my mac under tidy verse version 1.1.1.  When I updated to tidyverse 1.2.1 the following error is generated and the rendering stop.  If I reinstall version 1.1.1 the rendering works again.  Is there a fix for this?  The exact error is below:

! Package inputenc Error: Unicode char √ (U+221A)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.570 \end{verbatim}

Try running pandoc with --latex-engine=xelatex.
pandoc: Error producing PDF
Error: pandoc document conversion failed with error 43
Execution halted

Thank you.

Paco

**Comment by hadley** [comment]
This highly likely to be unrelated to tidyverse, and so this question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
