### ISSUE TITLE
error in lazy loading for tidyverse while installing tidyverse

### ISSUE THREAD

**Issue by genewch** [tidyverse/tidyverse#99]
Hello everyone,

I have this problem in installing tidyverse on R 3.3.3. Initially there were also error messages in package dependencies. Those problems were cleared after installing the dependencies. But I still got the errors below, related to lazy loading of tidyverse. Could anyone advise me?

I'm running R 3.3.3 on Raspberry pi 3 with Raspian Stretch.

> install.packages("tidyverse")
Installing package into ‘/home/pi/R/arm-unknown-linux-gnueabihf-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://mirrors.eliteu.cn/CRAN/src/contrib/tidyverse_1.2.1.tar.gz'
Content type 'application/x-gzip' length 61647 bytes (60 KB)
==================================================
downloaded 60 KB

* installing *source* package ‘tidyverse’ ...
** package ‘tidyverse’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Warning: S3 methods ‘as.col_spec.NULL’, ‘as.col_spec.character’, ‘as.col_spec.col_spec’, ‘as.col_spec.default’, ‘as.col_spec.list’, ‘format.col_spec’, ‘output_column.POSIXt’, ‘output_column.default’, ‘output_column.double’, ‘print.col_spec’, ‘print.collector’, ‘print.date_names’, ‘print.locale’ were declared in NAMESPACE but not found
Error in library.dynam(lib, package, package.lib) : 
  shared object ‘readr.so’ not found
ERROR: lazy loading failed for package ‘tidyverse’
* removing ‘/home/pi/R/arm-unknown-linux-gnueabihf-library/3.3/tidyverse’

The downloaded source packages are in
	‘/tmp/Rtmpj9q3de/downloaded_packages’
Warning message:
In install.packages("tidyverse") :
  installation of package ‘tidyverse’ had non-zero exit status

**Comment by ds-jim** [comment]
I have the same issue, did you ever get around it?

**Comment by HarrisonBP** [comment]
I'm getting the same error on a new instance of Rstudio server on AWS:

```
> install.packages("tidyverse", dependencies = T)
Warning in install.packages :
  unable to access index for repository https://R-Forge.R-project.org/src/contrib:
  cannot open URL 'https://R-Forge.R-project.org/src/contrib/PACKAGES'
Installing package into ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository https://R-Forge.R-project.org/src/contrib:
  cannot open URL 'https://R-Forge.R-project.org/src/contrib/PACKAGES'
trying URL 'https://cran.rstudio.com/src/contrib/tidyverse_1.2.1.tar.gz'
Content type 'application/x-gzip' length 61647 bytes (60 KB)
==================================================
downloaded 60 KB

* installing *source* package ‘tidyverse’ ...
** package ‘tidyverse’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Warning: S3 methods ‘as.col_spec.NULL’, ‘as.col_spec.character’, ‘as.col_spec.col_spec’, ‘as.col_spec.default’, ‘as.col_spec.list’, ‘format.col_spec’, ‘output_column.POSIXt’, ‘output_column.default’, ‘output_column.double’, ‘print.col_spec’, ‘print.collector’, ‘print.date_names’, ‘print.locale’ were declared in NAMESPACE but not found
Error in library.dynam(lib, package, package.lib) : 
  shared object ‘readr.so’ not found
ERROR: lazy loading failed for package ‘tidyverse’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.4/tidyverse’
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmphASgwR/downloaded_packages’
```

**Comment by ds-jim** [comment]
Hi Harrison, I'm not sure about the "unable to access index error you're getting but mine turned out to be an issue with the readr  file structure being locked. A previous installed that failed locked the folder from any further writing. The below code worked for me, good luck.

` #If "failed to create lock" is the returned error, install with the below code;`
`install.packages("readr", dependencies=TRUE, INSTALL_opts = c('--no-lock'))`

**Comment by HarrisonBP** [comment]
Hello Jim, thanks a TON! As for the "access index" part of the error, I had `setRepositories()` pointed incorectly when trying to troubleshoot the problem.

**Comment by ds-jim** [comment]
Haha, you're welcome. It was the same for me, I scratched my head for hours until I spotted failed to create lock was the key bit of information in the error.

**Comment by hadley** [comment]
You are always best of installing from a fresh R session with no packages loaded; unfortunately `install.packages()` almost-silently fails on windows when you have a binary package loaded in the current session.
